#KLI-59 速度指定クラスを作成する
KatLab-MiyazakiUniv/etrobocon2024 pull request #10
Opened 2024-06-09 11:20 UTC by CHIHAYATAKU

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
etrobocon2024/module/Calculatorディレクトリに，目標速度に対応するPWM値を算出するために，以下のソースファイルを追加．

- SpeedCalculator.cpp
- SpeedCalculator.h

etrobocon2024/testに以下のSpeedCalculatorクラスのテストファイルを追加．

- SpeedCalculatorTest.cpp

また，etrobocon2024/module/API/Controller.cpp，etrobocon2024/module/API/Controller.hに左右タイヤのpwm値を取得するためのメソッドを追加し，それに伴うテストをetrobocon2024/test/ControllerTest.cppに追加．

# 動作テスト
[実機テストNotionリンク](https://www.notion.so/uom-katlab/4160109455d54f5b9dc4c7b4541cbb18?pvs=4#e56344bf608243178d51bcc022a10c30)
## 実験結果
・sleep->0.1[s]でpwm更新
・（kp, ki , kd）= （0.004, 0.0000005, 0.0007）
・目標300[mm/s]．

上の条件で，大体平均300[mm/s]になった．
[実際の計測中のコンソール](https://www.notion.so/uom-katlab/4160109455d54f5b9dc4c7b4541cbb18?pvs=4#ac403bb847694705aff500cd20982a12)
## 添付資料
大量なのでNotionにまとめてあります．
[Notionリンク](https://www.notion.so/uom-katlab/4160109455d54f5b9dc4c7b4541cbb18?pvs=4#c51e525aa5d348c59f25a7089b3d5fcb)

2024-06-10 12:20 UTC, YKhm20020 requested changes
主にPWM値の double 型対応に関連することです。お願いします🙏

2024-06-10 12:20 UTC, molpui0726 commented on module/API/Controller.h
> +  static double getRightPwm();
```suggestion
  static double getRightMotorPwm();
```
他の変更に合わせるなら、ここはMotorの方がいいかな。

2024-06-10 12:20 UTC, molpui0726 commented on module/API/Controller.h
> +  static double getLeftPwm();
```suggestion
  static double getLeftMotorPwm();
```
ここもかな。

2024-06-10 12:20 UTC, YKhm20020 commented on module/API/Controller.cpp
> +  pwmOfArm = 0;
```suggestion
  pwmOfArm = 0.0;
```
上のを見た感じだと、double 型の変数をセットしてるみたいだから、一応 0.0 の方がいいかな。

2024-06-10 12:20 UTC, YKhm20020 commented on module/API/Controller.cpp
> +  pwmOfArm = 0;
```suggestion
  pwmOfArm = 0.0;
```
ここもかな。

2024-06-10 12:20 UTC, YKhm20020 commented on module/API/Controller.cpp
>  int Controller::limitPwmValue(const int value)
```suggestion
int Controller::limitPwmValue(const doble value)
```
PWM値関連を全部 double にしちゃっていいかも。

2024-06-10 12:20 UTC, YKhm20020 commented on module/API/Controller.h
>  #define CONTROLLER_H
これより下が直接の変更箇所じゃなかったから、一番近いここに書きます。
  /** PWM値の上限 */
  static const int MOTOR_PWM_MAX = 100;
  /** PWM値の下限 */
  static const int MOTOR_PWM_MIN = -100;
今こんな感じになってて、少し前のPWM値を全部double にするなら、ここもdoubleでいいかなと思います。

2024-06-10 16:48 UTC, CHIHAYATAKU commented on module/API/Controller.h
>  #define CONTROLLER_H
わかりました。
Measurerのpwmもdoubleに変更していいですか？

2024-06-10 17:42 UTC, CHIHAYATAKU commented on module/API/Controller.h
>  #define CONTROLLER_H
修正でdummy内のMotorのpwmもdouble型にしたのですが，そもそも公式がdouble型で扱っているかが分からないので不安です．

2024-06-11 01:20 UTC, bizyutyu commented on module/API/Controller.h
>  #define CONTROLLER_H
↓setPWMするときは、intじゃないといけないみたいです。
[リファレンス](https://www.toppers.jp/ev3pf/EV3RT_CXX_API_Reference/classev3api_1_1_motor.html)
ちなみに、PWMがdoubleの場所がある理由は、pid制御や速度制御の計算途中で小数点以下が切り落とされるのを防ぐためです。なので計算処理中はdoubleで扱って、setPWMに渡すときにintにキャストすれば問題ないと思う。
limitPwmValueとかをdoubleにするのは、好みかな。

2024-06-11 02:06 UTC, bizyutyu requested changes
いくつかあります。

2024-06-11 02:06 UTC, bizyutyu commented on module/API/Controller.cpp
> +void Controller::setRightMotorPwm(const double pwm)
全体的に命名規則揃えたほうが良い？
```
double inputPwm
```

2024-06-11 02:06 UTC, bizyutyu commented on module/API/Controller.cpp
>    leftWheel.setPWM(limitPwmValue(pwm));
ここも
```
leftWheel.setPWM(int(limitPwmValue(pwm)));
```

2024-06-11 02:06 UTC, bizyutyu commented on module/API/Controller.cpp
>    rightWheel.setPWM(limitPwmValue(pwm));
明示的にintにキャストしたほうが良いと思う。
```
rightWheel.setPWM(int(limitPwmValue(pwm)));
```

2024-06-11 02:06 UTC, bizyutyu commented on module/API/Controller.cpp
>    armMotor.setPWM(limitPwmValue(pwm));
ここも
```
armMotor.setPWM(int(limitPwmValue(pwm)));
```

2024-06-11 04:44 UTC, CHIHAYATAKU commented on module/API/Controller.cpp
>    rightWheel.setPWM(limitPwmValue(pwm));
了解です

2024-06-11 04:45 UTC, CHIHAYATAKU commented on module/API/Controller.cpp
> +void Controller::setRightMotorPwm(const double pwm)
そうですね．そろえておきます．

2024-06-11 05:29 UTC, CHIHAYATAKU commented
木村さん，高倉さんが指摘してくださったところを修正しました．
また，controller.cpp内で左右pwmを格納する際にMAX，MINを考慮できていなことに気づいたので修正しました．

2024-06-11 08:50 UTC, aridome222 requested changes
数か所気になるところがあるので、対応お願いします。

2024-06-11 08:50 UTC, aridome222 commented on module/Calculator/SpeedCalculator.h
> +  double calculaterightMotorPwmFromTargetSpeed();
ここも。
```suggestion
  double calculateRightMotorPwmFromTargetSpeed();
```

2024-06-11 08:50 UTC, aridome222 commented on module/Calculator/SpeedCalculator.h
> +  double calculateleftMotorPwmFromTargetSpeed();
ここも。
```suggestion
  double calculateLeftMotorPwmFromTargetSpeed();
```

2024-06-11 08:50 UTC, aridome222 commented on module/Calculator/SpeedCalculator.cpp
> +double SpeedCalculator::calculaterightMotorPwmFromTargetSpeed()
calculateとrightが混ざって見ずらいかな。
個人的には、Motor消して、calculateRightPwmFromTargetSpeed()でも良さそう。
```suggestion
double SpeedCalculator::calculaterightMotorPwmFromTargetSpeed()
```

2024-06-11 08:50 UTC, aridome222 commented on module/Calculator/SpeedCalculator.cpp
> +double SpeedCalculator::calculateleftMotorPwmFromTargetSpeed()
ここも。
```suggestion
double SpeedCalculator::calculateLeftMotorPwmFromTargetSpeed()
```

2024-06-11 09:53 UTC, CHIHAYATAKU commented on module/Calculator/SpeedCalculator.cpp
> +double SpeedCalculator::calculateleftMotorPwmFromTargetSpeed()
right、leftの書き間違いは見落としてました。修正します！

Motorの有無はcontrollerのgetLeft, Right, ArmMotorPwmメソッドに命名を統一するようにつけました。個人的には特に困らないのであればこのままでもいいかなと思います。

2024-06-11 11:05 UTC, YKhm20020 commented on module/API/Controller.h
>  #define CONTROLLER_H
返信遅れてしまって申し訳ないです🙇‍♂️
ご指摘ありがとうございます。計算過程ではdouble、渡すときにintでお願いします🙇‍♂️

2024-06-11 11:49 UTC, bizyutyu requested changes
追加でいくつか。

2024-06-11 11:49 UTC, bizyutyu commented on module/API/Controller.cpp
> +  rightWheel.setPWM(int(limitPwmValue(pwm)));
同じようなことをやってるlimitPwmValueがあるので、以下のように変更してほしいです。
それと、度々申し訳ないのだけど、static_castを使ったほうが、安全に型変換できるということに気づきました。
```suggestion
pwmOfRightWheel = limitPwmValue(pwm);
rightWheel.setPWM(static_cast<int>(pwmOfRightWheel));
```

2024-06-11 11:49 UTC, bizyutyu commented on module/API/Controller.cpp
> +  leftWheel.setPWM(int(limitPwmValue(pwm)));
ここも
```suggestion
pwmOfLeftWheel = limitPwmValue(pwm);
leftWheel.setPWM(static_cast<int>(pwmOfLeftWheel));
```

2024-06-11 11:49 UTC, bizyutyu commented on module/API/Controller.cpp
> +  armMotor.setPWM(int(limitPwmValue(pwm)));
ここもお願いします。
```suggestion
  pwmOfArm = limitPwmValue(pwm);
  armMotor.setPWM(static_cast<int>(pwmOfArm));
```

2024-06-11 11:49 UTC, bizyutyu commented on test/SpeedCalculatorTest.cpp
> +    controller.setLeftMotorPwm(0.0);
こう書いても同じ？(他のところも)
```suggestion
    Controller::stopMotor();
```

2024-06-11 12:44 UTC, Negimarge reviewed
Max,Minの分岐をlimitPwmValueに置き換えるのをやったらOKだと思うー

2024-06-11 14:45 UTC, CHIHAYATAKU commented on test/SpeedCalculatorTest.cpp
> +    controller.setLeftMotorPwm(0.0);
処理は同じですが，メソッドの意味合いが違う気がします．個人的にはsetの方がしっくりきます．

2024-06-11 14:45 UTC, CHIHAYATAKU commented on module/API/Controller.cpp
> +  armMotor.setPWM(int(limitPwmValue(pwm)));
了解です．

2024-06-11 15:10 UTC, CHIHAYATAKU commented
指摘して頂いたところは直しました．漏れがあったらすみません．
また，追加で，Controllerの車輪モータを止める「stopMotor」というメソッドがあったのですが，アームを止める方は「stopArmMotor」となっていて，区別しづらいと思ったので，「stopWheelsMotor」に変更しました．

2024-06-11 16:14 UTC, aridome222 approved these changes
いろいろ修正お疲れ様！LGTM！
![LGTM](https://image.lgtmoon.dev/36247)

2024-06-11 18:13 UTC, Negimarge approved these changes
LGTM

2024-06-12 00:09 UTC, bizyutyu approved these changes
レビュー対応お疲れ様です！LGTM！！
![LGTM](https://image.lgtmoon.dev/139186)

2024-06-12 03:08 UTC, YKhm20020 approved these changes
遅くなってごめんなさい、LGTMです！
1週間イテレーションで実装・動作確認と大変だったと思います、お疲れ様でした！
![213916](https://github.com/KatLab-MiyazakiUniv/etrobocon2024/assets/128010507/e7c0c63c-703b-43f2-8eca-3daf5658e549)

2024-06-12 03:47 UTC, merged