close #KLI-61 回頭の親クラス、子クラスの作成(角度指定)
KatLab-MiyazakiUniv/etrobocon2024 pull request #12
Opened 2024-06-09 17:18 UTC by takahashitom

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点

角度とPWM値を指定して回頭動作を行うための親クラスを定義したソースファイルを、module/Motionに追加
-Rotation.h
-Rotation.cpp

角度とPWM値を指定して回頭動作を行うための子クラスを定義したソースファイルを、module/Motionに追加
-PwmRotation.h
-PwmRotation.cpp

走行システムで統一する情報をまとめたファイルを、module/commonに追加
-SystemInfo.h

Rotationクラス、PwmRotationクラスのテストファイルを、testに追加
-PwmRotationTest.cpp

# 動作テスト
https://www.notion.so/uom-katlab/d16c1efb8c7f4842a41fa9a2ca9ca014?pvs=4#6c803151e9a7433e933aee41fa186fdc

## 実験結果
角度、PWM値を設定し、回頭動作を行うことができた。
布面上ではタイヤが上手く回転せずに、動作にずれが生じてしまう場合があることが確認された。

2024-06-10 11:17 UTC, YKhm20020 requested changes
いくつか細かいところがあるので、お願いします🙏

2024-06-10 11:17 UTC, molpui0726 commented on test/PwmRotationTest.cpp
> + * @author Negimarge
```suggestion
 * @author takahashitom
```
これは合ってる？
もし根木原くんに手伝ってもらってても、担当分でファイルを扱ってるなら自分の名前書いていいよ🙆‍♀️

2024-06-10 11:17 UTC, molpui0726 commented on module/common/SystemInfo.h
> + * @author desty505 bizyutyu
```suggestion
 * @author takahashitom
```
ここは多分変え忘れかな

2024-06-10 11:17 UTC, molpui0726 commented on test/PwmRotationTest.cpp
> +
```suggestion
// PWM値を0に設定して回頭するテスト
```
他のテストではテスト内容があるから、ここも。
名前はもっといい感じのあれば変えてください。

2024-06-10 11:17 UTC, molpui0726 commented on test/PwmRotationTest.cpp
> +
```suggestion
// PWM値をマイナスに設定して回頭するテスト
```
こんな感じ？

2024-06-10 11:17 UTC, molpui0726 commented on test/PwmRotationTest.cpp
> +
```suggestion
回頭角度を0に設定して回頭するテスト
```
こんな感じ？

2024-06-10 11:17 UTC, YKhm20020 commented on test/PwmRotationTest.cpp
> +
```suggestion
360度回頭するテスト
```
いい感じの名前浮かびませんでした。

2024-06-10 11:30 UTC, takahashitom commented on test/PwmRotationTest.cpp
> + * @author Negimarge
すいません。コピペしてそのままでした。
修正しておきます。

2024-06-10 11:48 UTC, takahashitom commented on module/common/SystemInfo.h
> + * @author desty505 bizyutyu
レビューありがとうございます。
修正しました。
ca34f3360b9abac3bbdc658af3b26edec4916b5f

2024-06-10 11:49 UTC, takahashitom commented on test/PwmRotationTest.cpp
> +
レビューありがとうございます。
修正しました。83a7556369235b8b513bd143c93419e06cd1b294

2024-06-11 05:42 UTC, aridome222 reviewed
コードは問題ないと思います。
Notionで、角度を90度、PWM値を50度にした場合、布だとスムーズに回頭しないってあったけど、PWM値を50より大きくした場合はどうだった？
おそらく、もっとPWM値を上げたらスムーズに動きそう。ずれは生じるかもだけど。
あと、30度とか60度の場合はずれに関してどうだったか気になります。

2024-06-11 10:01 UTC, takahashitom commented
> コードは問題ないと思います。 Notionで、角度を90度、PWM値を50度にした場合、布だとスムーズに回頭しないってあったけど、PWM値を50より大きくした場合はどうだった？ おそらく、もっとPWM値を上げたらスムーズに動きそう。ずれは生じるかもだけど。 あと、30度とか60度の場合はずれに関してどうだったか気になります。

はい。PWM値を大きくした場合、スムーズに回頭することを確認しています。しかし、動きに勢いがつきすぎてしまい、ずれが生じてしまいました。
PWM値を100に設定した状態だと、回頭位置、角度共に大きくずれが生じました。また、PWM値が70程度まで、勢いによるずれが確認され、60程度からモータが動きずらい感じがありました。PWM値が50のときが、モータが動きさえすればきれいに回頭したかなといった感じです。PWM値を30程度まで落とすと、モータを動かすパワーが足りず、タイヤが動かなかったです。

回頭角度を小さくした場合は、一回一回のずれは小さくなりました。しかし、30度回頭を３回連続で行い90度回頭を再現しようとすると、回頭角度を90度に設定した場合と同程度のずれになってしまいました。また、回頭動作の間に若干のラグが生じました。（１回目の30度回頭と２回目の30度回頭の間に、一瞬動きがつんのめる様な感じがあったといった感じ）

他のパターンの動画も撮っておけばよかったです。。。すみません。
後日、他パターンの動画も Notion の方にアップしようと思います。

2024-06-11 11:23 UTC, YKhm20020 approved these changes
修正ありがとうございます。
短い期間で実装、実機動作といそがしかったと思います、お疲れ様でした。
プログラムは問題なさそうなので、LGTM出します！
![214057](https://github.com/KatLab-MiyazakiUniv/etrobocon2024/assets/128010507/7ae3e01f-fe36-4ec2-ac31-f9d9a0793d7a)

2024-06-11 12:58 UTC, bizyutyu requested changes
遅くて申し訳ないけど、いくつか修正お願いします。

2024-06-11 12:58 UTC, bizyutyu commented on module/Motion/PwmRotation.cpp
> +bool PwmRotation::isMetPrecondition()
以下のように変えたほうが良いと思う。
```suggestion
bool PwmRotation::isMetPreCondition()
```

2024-06-11 12:58 UTC, bizyutyu commented on module/Motion/PwmRotation.cpp
> +bool PwmRotation::isMetPostcondition(double targetLeftDistance, double targetRightDistance,
ここもお願いします。
```suggestion
bool PwmRotation::isMetPostCondition(double targetLeftDistance, double targetRightDistance,
```

2024-06-11 12:58 UTC, bizyutyu commented on module/Motion/PwmRotation.h
> +  bool isMetPrecondition() override;
ここも。
```suggestion
  bool isMetPreCondition() override;
```

2024-06-11 12:58 UTC, bizyutyu commented on module/Motion/PwmRotation.h
> +  bool isMetPostcondition(double initLeftMileage, double initRightMileage, int leftSign,
ここも
```suggestion
  bool isMetPostCondition(double initLeftMileage, double initRightMileage, int leftSign,
```

2024-06-11 12:58 UTC, bizyutyu commented on module/common/SystemInfo.h
> +static constexpr int ANGLE_SERVER_PORT = 10338;  // 角度算出用サーバのポート番号
おそらくRotation.hでincludeしてるから、このファイル追加したと思うんだけど、現状使ってないものは削除するか、コメントを残して欲しい。削除したほうがスッキリして良いかも。
ちなみに残すのは現状以下。
```
static constexpr double RADIUS = 50.0;  // 車輪の半径[mm]
static constexpr double TREAD = 125.0;  // 走行体のトレッド幅（両輪の間の距離）[mm]
```
そして、Mileage.cppにも```static constexpr double RADIUS = 50.0;  // 車輪の半径[mm]```があるので、それを消して、```#include "SystemInfo.h"```を追加すれば、SystemInfo.hにまとめている走行システムで統一する情報を上手く使った実装になると思います。

下は雑だけどコメントの例です。
```suggestion
// 現状未使用
// ロボコンの部屋で取得した輝度
static constexpr int BLACK_BRIGHTNESS = 3;   // 黒の輝度
static constexpr int WHITE_BRIGHTNESS = 93;  // 白の輝度

static constexpr double RADIUS = 50.0;  // 車輪の半径[mm]
static constexpr double TREAD = 125.0;  // 走行体のトレッド幅（両輪の間の距離）[mm]

// 現状未使用
static constexpr char RAS_PI_IP[16] = "172.20.1.1";

// 現状未使用
static constexpr int ANGLE_SERVER_PORT = 10338;  // 角度算出用サーバのポート番号
```

2024-06-11 13:25 UTC, Negimarge commented on module/Motion/PwmRotation.cpp
> +bool PwmRotation::isMetPostcondition(double targetLeftDistance, double targetRightDistance,
postかなあ、後条件というか完了条件だけどいい英語があればお願いします

2024-06-11 15:41 UTC, takahashitom commented on module/Motion/PwmRotation.cpp
> +bool PwmRotation::isMetPostcondition(double targetLeftDistance, double targetRightDistance,
継続条件の判定ともとれるので、”isMetContinuationCondition” あたりが妥当なところかと思いますが、少し長いかもです。

2024-06-11 15:46 UTC, aridome222 commented
> > コードは問題ないと思います。 Notionで、角度を90度、PWM値を50度にした場合、布だとスムーズに回頭しないってあったけど、PWM値を50より大きくした場合はどうだった？ おそらく、もっとPWM値を上げたらスムーズに動きそう。ずれは生じるかもだけど。 あと、30度とか60度の場合はずれに関してどうだったか気になります。
> 
> はい。PWM値を大きくした場合、スムーズに回頭することを確認しています。しかし、動きに勢いがつきすぎてしまい、ずれが生じてしまいました。 PWM値を100に設定した状態だと、回頭位置、角度共に大きくずれが生じました。また、PWM値が70程度まで、勢いによるずれが確認され、60程度からモータが動きずらい感じがありました。PWM値が50のときが、モータが動きさえすればきれいに回頭したかなといった感じです。PWM値を30程度まで落とすと、モータを動かすパワーが足りず、タイヤが動かなかったです。
> 
> 回頭角度を小さくした場合は、一回一回のずれは小さくなりました。しかし、30度回頭を３回連続で行い90度回頭を再現しようとすると、回頭角度を90度に設定した場合と同程度のずれになってしまいました。また、回頭動作の間に若干のラグが生じました。（１回目の30度回頭と２回目の30度回頭の間に、一瞬動きがつんのめる様な感じがあったといった感じ）
> 
> 他のパターンの動画も撮っておけばよかったです。。。すみません。 後日、他パターンの動画も Notion の方にアップしようと思います。

なるほど！いろいろ調査してくれてありがとう。色々質問しちゃったけど、今回のタスクでは回頭できることが完了条件だから、そこまで気にしなくていいよ。
これから先のことを話すと、PWM値が50だと少し遅いから、60以上が良いかも。その場合のずれに関しては、今後の調整でやっていくと思うんだけど、例えば目標角度90度に対して、PWM値を60に固定した場合に、指定角度を何度にするのが最も安定して目標角度で回頭できるかを検証する必要が出てくるよ。回頭使う場面は、ダブルループとかブロックエリアが主だから、今後のタスクで細かく調整すればOK。

2024-06-11 15:50 UTC, aridome222 approved these changes
実装と実機での調査お疲れさま！
![LGTM](https://image.lgtmoon.dev/123334)

2024-06-11 15:57 UTC, takahashitom commented on module/common/SystemInfo.h
> +static constexpr int ANGLE_SERVER_PORT = 10338;  // 角度算出用サーバのポート番号
レビューありがとうございます。
自分も削除した方がスッキリしていいと思ったので、現状つかっていない情報は削除しました。
使用する情報が増えた場合は、その時追加していく形でお願いします。
c700fe0bc5efafd7b5f9f168985bf3a8bf5c3c1b

2024-06-11 18:11 UTC, Negimarge commented on module/Motion/PwmRotation.cpp
> +bool PwmRotation::isMetPostcondition(double targetLeftDistance, double targetRightDistance,
そうなんよな
去年も俺がそうなったんよな
まあええか

2024-06-11 18:12 UTC, Negimarge approved these changes
LGTM

2024-06-11 18:49 UTC, KakinokiKanta approved these changes
高倉くんのレビューに対応してもらって、Loggerがマージされたら、コメント外してもらえば問題ないと思う！
後、回頭角度のずれにかんしては、ずれる角度がある程度一定なら、実際にさせたい回頭角度と、指定角度を分けて考えれば大丈夫だから、そこまで気にしなくても良いよ
![LGTM](https://image.lgtmoon.dev/250835)

2024-06-12 03:13 UTC, takahashitom commented on module/Motion/PwmRotation.h
> +  bool isMetPostcondition(double initLeftMileage, double initRightMileage, int leftSign,
レビューありがとうございます。
修正しました。
isMetPostCondition に関しては、関数の内容が事後条件の判定というより、継続条件の判定であったため、isMetContCondition としました。
688749b0d78779d5992e7c54c9e2e321e05944f6

2024-06-12 03:46 UTC, bizyutyu approved these changes
レビュー対応お疲れ様！LGTM！！
![LGTM](https://image.lgtmoon.dev/201775)

2024-06-12 03:46 UTC, merged