close #KLI-85 エッジを切り替えるクラスの作成
KatLab-MiyazakiUniv/etrobocon2024 pull request #15
Opened 2024-06-19 04:20 UTC by takahashitom

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
エッジを切り替えるためのクラスを定義したソースファイルを、module/Motion に追加
- EdgeChanging.h
- EdgeChanging.cpp

EdgeChangingクラスのテストファイルを、test に追加
- EdgeChangingTest.cpp

## 添付資料

2024-06-20 10:12 UTC, YKhm20020 approved these changes
細かいとこだしコメントのところだけなので先にApprove出しておきます。
![211466](https://github.com/KatLab-MiyazakiUniv/etrobocon2024/assets/128010507/e55f8055-3e8a-403b-9c81-2eb992bafa55)

2024-06-20 10:12 UTC, YKhm20020 commented on module/Motion/EdgeChanging.h
> +  bool nextEdge;     // 切り替え後のエッジ(true:左エッジ，false:右エッジ)
```suggestion
  bool& isLeftEdge;  // エッジの左右判定(true:左エッジ, false:右エッジ)
  bool nextEdge;     // 切り替え後のエッジ(true:左エッジ, false:右エッジ)
```

細かくてごめんなさい。
なんでかがわかんないんだけど、nextEdge の 「左エッジ, false」のカンマが統一されてないかも？
僕のキーボードからは、半角カンマと半角スペースで合わせたらこんな感じになってる。
前年以前からこの状態かも。ごめん。

2024-06-20 10:12 UTC, YKhm20020 commented on module/Motion/EdgeChanging.h
> +   * @param _nextEdge 切り替え後のエッジ(true:左エッジ，false:右エッジ)
```suggestion
   * @param _isLeftEdge エッジの左右判定(true:左エッジ, false:右エッジ)
   * @param _nextEdge 切り替え後のエッジ(true:左エッジ, false:右エッジ)
```

nextEdge の方が全角になってるのかな？

2024-06-20 11:38 UTC, takahashitom commented on module/Motion/EdgeChanging.h
> +   * @param _nextEdge 切り替え後のエッジ(true:左エッジ，false:右エッジ)
レビューありがとうございます。
修正しました。
be577e8a9b7c0fcb132379bf1480999da0cab9a3

2024-06-24 07:20 UTC, aridome222 approved these changes
LGTM！

2024-06-24 15:13 UTC, bizyutyu requested changes
細かいですが、一つだけ。

2024-06-24 15:13 UTC, bizyutyu commented on test/EdgeChangingTest.cpp
> +#include <cmath>
これ要るのでしょうか？
```suggestion
```

2024-06-25 05:01 UTC, takahashitom commented on test/EdgeChangingTest.cpp
> +#include <cmath>
レビューありがとうございます。
要らなかったです。
修正しました。
https://github.com/KatLab-MiyazakiUniv/etrobocon2024/pull/15/commits/69bfc9ffb3a91401687d47db5f7633026fcf92ff

2024-06-25 08:40 UTC, bizyutyu approved these changes
L☆G☆T☆M
![LGTM](https://image.lgtmoon.dev/75815)

2024-06-26 10:39 UTC, merged