close #KLI-55 直進・後退に関するクラスの作成
KatLab-MiyazakiUniv/etrobocon2024 pull request #16
Opened 2024-06-19 05:21 UTC by bizyutyu

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
- 直進・後退に関する以下のクラスをに作成し、module/Motion/に追加。
 - 親クラス（Straight.h, Straight.cpp）
 - 子クラス
  - 色指定直進（ColorStraight.h, ColorStraight.cpp）
  - 距離指定直進（DistanceStraight.h, DistanceStraight.cpp）
  - 
# 動作テスト
未実施

## 結果
複数の速度について確認する
出来れば、走行可能な最低指定速度を確認しておきたい所。

## 添付資料

2024-06-23 15:26 UTC, CHIHAYATAKU requested changes
LineTracingとStraightで合わせたいので，よろしくお願いします．
どちらかに合わせたほうが良いと思うので，合わせるまでは一応Recested Changeで出しておきます．

2024-06-23 15:26 UTC, CHIHAYATAKU commented on module/Motion/DistanceStraight.cpp
> +  return false;
ここも同じです．あと，変数*Distanceがdouble型になっているので，fabsの方がよいかもしれないです．

```suggestion
  // 現在の走行距離が目標走行距離に達していればfalseを返す
  // 左右どちらか
  if((fabs(Mileage::calculateWheelMileage(currentRightMotorCount) - initialRightDistance) >= targetDistance)
     || (abs(Mileage::calculateWheelMileage(currentLeftMotorCount) - initialLeftDistance) >= targetDistance)) {
    return false;
  }

  // 現在の走行距離が目標走行距離に達していない場合trueを返す
  return true;
```

ついでに確認したいのですが，DistanceLineTracingの継続条件では，
```
if(fabs(Mileage::calculateMileage(measurer.getRightCount(), measurer.getLeftCount())
- initDistance)
return false;
```
のように，車輪ごとに判定するのではなく平均して判定するようにしているのですが，どちらがよいですか？
合わせておきたいです．

2024-06-23 15:26 UTC, CHIHAYATAKU commented on module/Motion/ColorStraight.cpp
> +}
継続条件を満たしているかの関数なので，通常の返り値をtrueにした方がよさそうです！
```suggestion
bool ColorStraight::isMetContinuationCondition()
{
  COLOR color = ColorJudge::getColor(measurer.getRawColor());
  if(color == targetColor) {
    return false;
  }

  return true;
}
```

2024-06-23 15:26 UTC, CHIHAYATAKU commented on module/Motion/DistanceStraight.cpp
> +  currentLeftDistance = Mileage::calculateWheelMileage(currentLeftMotorCount);
currentRightDistance，currentLeftDistanceはそれぞれ `Mileage::calculateWheelMileage(currentRightMotorCount)`
`Mileage::calculateWheelMileage(currentLeftMotorCount)`
で値をセットしているだけなので，インスタンス変数として持たせる必要がないかもしれません．
見落としていたらすみません．
```suggestion
  currentRightMotorCount = measurer.getRightCount();
  currentLeftMotorCount = measurer.getLeftCount();
```

2024-06-23 15:26 UTC, CHIHAYATAKU commented on module/Motion/Straight.h
> +  double currentLeftDistance;              // 現在左輪距離
上の変更が可能であればcurrentRightDistance，currentLeftDistanceは保持する必要は無くせると思います．
```suggestion
  int currentRightMotorCount;              // 現在右モーター角位置
  int currentLeftMotorCount;               // 現在左モーター角位置
```

2024-06-24 15:06 UTC, aridome222 approved these changes
LGTM!

2024-06-24 15:25 UTC, CHIHAYATAKU approved these changes
話し合って決めることができたのでよかったです！
僕は問題ないと思います
![LGTM](https://image.lgtmoon.dev/250396)

2024-06-25 13:27 UTC, negiuniv approved these changes
LGTM

2024-06-25 18:29 UTC, KakinokiKanta approved these changes
遅くなってしまい、申し訳ない。
LGTM

2024-06-26 10:38 UTC, merged