close #KLI-82 キャリブレーションクラスを実装する
KatLab-MiyazakiUniv/etrobocon2024 pull request #17
Opened 2024-06-19 11:03 UTC by takahashitom

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
キャリブレーションからスタートまでを担当するクラスを定義したソースファイルを module に追加
- Calibrator.h
- Calibrator.cpp

Calibratorクラスのテストファイルを test に追加
- CalibratorTest.cpp

test/dummy/ev3api_button.cpp にボタンの状態を更新する処理を追加

# 動作テスト

## 実験方法

## 実験結果

## 添付資料

2024-06-23 16:49 UTC, CHIHAYATAKU requested changes
本当に細かいですが，よろしくお願いします．

2024-06-23 16:49 UTC, CHIHAYATAKU commented on module/Calibrator.h
> +};
setも関数名に入れたほうが分かりやすいです！
```suggestion
  /**
   * @brief 左右ボタンでLRコースを選択してisLeftCourseをセットする
   */
  void selectAndSetCourse();

  /**
   * @brief 黒と白の輝度を測定して目標輝度を求めtargetBrightnessをセットする
   */
  void measureAndSetTargetBrightness();
};
```

2024-06-24 10:05 UTC, takahashitom commented on module/Calibrator.h
> +};
レビューありがとうございます。
修正しました。
https://github.com/KatLab-MiyazakiUniv/etrobocon2024/pull/17/commits/ed6d065b700a5f185da0ac6af826261808fec285

2024-06-24 13:55 UTC, CHIHAYATAKU approved these changes
僕は問題ないと思います
![LGTM](https://image.lgtmoon.dev/250396)

2024-06-24 15:30 UTC, aridome222 approved these changes
LGTM!

2024-06-25 08:37 UTC, bizyutyu approved these changes
OKだと思います。LGTM！
![LGTM](https://image.lgtmoon.dev/252595)

2024-06-25 13:40 UTC, negiuniv approved these changes
getIsLeftCourseにちょっと思ったけどロボコンの命名規則ならあってるわ
LGTM

2024-06-26 10:39 UTC, merged