close #KLI-56 ライントレースの親子クラスの作成(距離指定, 色指定)
KatLab-MiyazakiUniv/etrobocon2024 pull request #18
Opened 2024-06-23 14:17 UTC by CHIHAYATAKU

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
etrobocon2024/module/Motion/ディレクトリ直下に，色指定・距離指定ライントレースを行うために，以下のファイルを追加した．

- LineTracing.cpp
- LineTracing.h
- ColorLineTracing.cpp
- ColorLineTracing.h
- DistanceLineTracing.cpp
- DistanceLineTracing.h

また，ライントレースクラスに関するテストを行うために，test/ディレクトリ直下に以下のファイルを追加した．

- ColorLineTracingTest.cpp
- DistanceLineTracingTest.cpp

# 動作テスト
https://www.notion.so/uom-katlab/bcbe6fdfa6de4d308c6fca58b701613c?pvs=4#980a60ebbe2146c6853573c7d760a180
## 実験結果
ライントレースが行えることは確認しました．
細かい調整は，csvファイルを読み込めるようになってからでお願いします．
## 添付資料
https://www.notion.so/uom-katlab/bcbe6fdfa6de4d308c6fca58b701613c?pvs=4#70d608fcfffb454e8c4b1a236d5cde2f

2024-06-24 13:22 UTC, YKhm20020 requested changes
一部コメントと、他の方の意見募集中のところあります。
抽象クラスについては、「C++ 純粋仮想関数」とかで調べると出てくると思います。
変更箇所多かったですね、お疲れ様です🙇‍♂️

2024-06-24 13:22 UTC, YKhm20020 commented on module/Motion/LineTracing.h
> +  virtual bool isMetPreCondition(double targetSpeed) = 0;
```suggestion
    /**
   * @brief ライントレースする際の事前条件判定をする
   * @param targetSpeed 目標速度
   * @note オーバーライド必須
   */
  virtual bool isMetPreCondition(double targetSpeed) = 0;
```
正しくはこう？
細かいけど🙏

2024-06-24 13:22 UTC, YKhm20020 commented on test/ColorLineTracingTest.cpp
> +  // 少し走ってから指定色を取得するテストケース
```suggestion
  // 少し走ってから指定色を取得するテストケース (左エッジ走行)
```
細かいしコメントのところだけど、下と同じテストケース名になってる。
runLeftEdge, runRightEdge の意味を汲み取れるように変更お願いします🙏

2024-06-24 13:22 UTC, YKhm20020 commented on test/ColorLineTracingTest.cpp
> +  // 少し走ってから指定色を取得するテストケース
```suggestion
  // 少し走ってから指定色を取得するテストケース (右エッジ走行)
```
ここも。

2024-06-24 13:22 UTC, YKhm20020 commented on test/ColorLineTracingTest.cpp
> +  // 少し走ってから指定色を取得するテストケース（バック）
```suggestion
  // 少し走ってから指定色を取得するテストケース（バック、左エッジ）
```

2024-06-24 13:22 UTC, YKhm20020 commented on test/ColorLineTracingTest.cpp
> +  // 少し走ってから指定色を取得するテストケース（バック）
```suggestion
  // 少し走ってから指定色を取得するテストケース（バック、右エッジ）
```

2024-06-24 13:22 UTC, YKhm20020 commented on test/DistanceLineTracingTest.cpp
> +  // 目標距離までライントレースを行うテストケース
```suggestion
  // 目標距離までライントレースを行うテストケース (左エッジ走行)
```

2024-06-24 13:22 UTC, YKhm20020 commented on test/DistanceLineTracingTest.cpp
> +  // 目標距離までライントレースを行うテストケース
```suggestion
  // 目標距離までライントレースを行うテストケース (右エッジ走行)
```

2024-06-24 13:22 UTC, YKhm20020 commented on test/DistanceLineTracingTest.cpp
> +  // 目標距離までライントレースを行うテストケース（バック）
```suggestion
  // 目標距離までライントレースを行うテストケース（バック、左エッジ）
```

2024-06-24 13:22 UTC, YKhm20020 commented on test/DistanceLineTracingTest.cpp
> +  // 目標距離までライントレースを行うテストケース（バック）
```suggestion
  // 目標距離までライントレースを行うテストケース（バック、右エッジ）
```

2024-06-24 13:22 UTC, YKhm20020 commented on module/Motion/LineTracing.h
> +  virtual void logRunning();
```suggestion
  virtual void logRunning() = 0;
```
純粋仮想関数は =0 が必要だと思うんですが、返り値の型が void ならいらないとかってありましたっけ？
他の方の意見募集中です🙏
参考文献:
https://cpp-lang.sevendays-study.com/ex-day6.html
https://www.ibm.com/docs/ja/i/7.4?topic=only-abstract-classes-c

2024-06-24 13:43 UTC, CHIHAYATAKU commented
変更したファイルが多くなっていますが、イテレーション中にKLI-86をmergeする前のmainをプルしてして、途中でKLI-86をmergeした後のmainを取り込んだため、このようになりました。
コンフリクトが起きるかもしれないので、申し訳ないですがよろしくお願いします🙇

2024-06-24 14:15 UTC, CHIHAYATAKU commented on module/Motion/LineTracing.h
> +  virtual void logRunning();
参考文献を見たところ，実装が省略されている純粋仮想関数は=0が必要なのは確認しましたが，非純粋仮想関数（不純仮想関数?）については特に言及されていないようでした．
見落としがあるかもしれませんが，言及されていないなら=0はいらないのではないでしょうか．

今回は，LineTracing.cppでlogRunning()の実装はしているので，=0は無くてもよいのではと思います．
他の方の意見も聞きたいです！

2024-06-24 14:17 UTC, takuchi17 commented
木村さんにご指摘いただいた箇所を修正しました．
https://github.com/KatLab-MiyazakiUniv/etrobocon2024/pull/18/commits/ddb4625d8134f61f6fbe4d8ef0d1e3da61f07a61

2024-06-24 15:18 UTC, aridome222 approved these changes
LGTM！

2024-06-24 15:22 UTC, bizyutyu approved these changes
大丈夫だと思う！LGTM！！
![LGTM](https://image.lgtmoon.dev/252462)

2024-06-25 14:00 UTC, negiuniv approved these changes
純粋仮想関数のとこにはコメント残した
他は大丈夫そう
LGTM

2024-06-25 14:00 UTC, negiuniv commented on module/Motion/LineTracing.h
> +  virtual void logRunning();
実装ない奴だけでいいと思う
virtualつけてて動的バインディングだから継承後の関数にoverrideつければ問題ない

2024-06-25 15:24 UTC, YKhm20020 reviewed
純粋仮想関数のところも答えてもらってありがとうございます。
遅くなってごめんなさい、LGTMです🙇
![135436](https://github.com/KatLab-MiyazakiUniv/etrobocon2024/assets/128010507/f90ad2b8-3d8f-43c0-8980-b033a4f19835)

2024-06-25 15:24 UTC, YKhm20020 approved these changes

2024-06-25 18:30 UTC, KakinokiKanta approved these changes
遅くなってしまい、マジで申し訳ない...
特に問題ないと思う。
LGTM!!

2024-06-26 10:39 UTC, merged