close #KLI-133 スリープの実装
KatLab-MiyazakiUniv/etrobocon2024 pull request #24
Opened 2024-07-03 14:56 UTC by YKhm20020

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
自タスクスリープの動作を行う Sleeping.cpp および Sleeping.h を実装。
テストファイルはなし。

2024-07-03 15:14 UTC, bizyutyu approved these changes
お疲れ様です。LGTM！
![LGTM](https://image.lgtmoon.dev/246671)

2024-07-03 17:33 UTC, KakinokiKanta requested changes
1か所だけ変なところあるんだけど、この状態じゃないと動かない？

2024-07-03 17:33 UTC, KakinokiKanta commented on module/Motion/Sleeping.cpp
> +#include "Timer.h"
```suggestion
```
ヘッダファイルでも読み込んでるんだけど、こっちでも読み込まないと動かないんだっけ？

2024-07-03 17:39 UTC, YKhm20020 commented on module/Motion/Sleeping.cpp
> +#include "Timer.h"
SleepのGoogle testがないので実機でどうなるかを確認しないといけませんが、おっしゃるとおり、ヘッダファイルにも記述があるので、動く可能性が高いです。
消した状態にします、ありがとうございます🙇

2024-07-04 01:29 UTC, TE-kounegihara submitted a review, later dismissed
コマンドには必ずパラメータの説明が必要
調整時これ何ってなる

2024-07-04 01:29 UTC, TE-kounegihara commented on module/MotionParser.cpp
> +      Sleeping* sl = new Sleeping(atoi(params[1]));
parmans[1]の説明がいる
//スリープ時間(ミリ秒)

2024-07-04 01:33 UTC, negiuniv requested changes, later dismissed
調整時わからなくなるからコマンドのパラメータの説明が必要

2024-07-04 01:33 UTC, negiuniv commented on module/MotionParser.cpp
> +      Sleeping* sl = new Sleeping(atoi(params[1]));
パラメータの説明が必要
// スリープ時間(ミリ秒)

2024-07-04 07:00 UTC, Negimarge approved these changes
LGTM

2024-07-04 07:42 UTC, KakinokiKanta approved these changes
私は石丸さんを応援します
![LGTM](https://image.lgtmoon.dev/254204)

2024-07-04 07:43 UTC, aridome222 approved these changes
LGTM!

2024-07-04 07:45 UTC, merged