#close KLI-155 モータ停止コマンドの実装
KatLab-MiyazakiUniv/etrobocon2024 pull request #29
Opened 2024-07-28 05:04 UTC by negiuniv

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
両輪のpwm値を0にしてダミーをリセットするResetWheelsMotorPwm.cppとResetWheelsMotorPwm.hを追加
両輪のpwm値を0にしてダミーをストップするResetWheelsMotorPwm.cppとResetWheelsMotorPwm.hを追加
Straight.cpp, Rotation.cpp, LineTracing.cppから controller.stopWheelsMotor();をコメントアウト

# 動作テスト
テストいじらなくても通った
呼び出しだけの関数より、テストは作成していない

2024-07-30 03:38 UTC, takahashitom requested changes
お疲れ様です。
問題ないと思います。
ちょっとしたとこがあったので、そこだけお願いします。

2024-07-30 03:38 UTC, takahashitom commented on module/Motion/StopWheelsMotor.cpp
> + * @author YourName
ちょっとしたとこです。
```suggestion
 * @author Negimarge
```

2024-07-30 11:36 UTC, aridome222 approved these changes
LGTM!
![LGTM](https://image.lgtmoon.dev/205373)

2024-07-31 02:33 UTC, takahashitom approved these changes
お疲れ様です。
問題ないと思います。

2024-07-31 04:03 UTC, keiya121 commented
お疲れ様です。ありがとうございます。
![タケシLGTM](https://github.com/user-attachments/assets/976f870c-21ae-492c-8187-f15e32976885)

2024-07-31 04:38 UTC, keiya121 approved these changes

2024-08-02 09:33 UTC, KakinokiKanta approved these changes
LGTM

2024-08-05 05:09 UTC, merged