カメラ撮影機能の実装
KatLab-MiyazakiUniv/etrobocon2024 pull request #30
Opened 2024-07-31 16:22 UTC by bizyutyu

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
```front_camera```ディレクトリを追加

# 動作テスト
```front_camera/```ディレクトリで```make image```を実行して、```front_camera/image/```にフロントカメラで撮影した画像が保存できることを確認しました。

2024-08-05 05:23 UTC, bizyutyu reviewed
遅くなって申し訳ない
処理の中身は特に問題ないと思う
質問にだけ答えてくれたら
by @KakinokiKanta

2024-08-05 05:23 UTC, bizyutyu commented on front_camera/front_camera/camera_interface.py
> +    def __init__(self, camera_id=0, data_format: str = "RGB888", size: Tuple[int, int] = (1640, 1232)) -> None:
ここの(1640, 1232)ってところ、取得する画像のサイズ？
API規約には、800×600って書いてあると思うんだけど

2024-08-05 10:31 UTC, YKhm20020 requested changes
本日対面でお聞きした箇所だけマークつけています。よろしくお願いいたします。

2024-08-05 10:31 UTC, YKhm20020 commented on front_camera/front_camera/capture_image.py
> +    resize = (640, 480)
```suggestion
    resize = (800, 600)
```
修正用で出しておきます

2024-08-05 10:31 UTC, YKhm20020 commented on front_camera/front_camera/capture_image.py
> +    def __init__(self, camera_id=0, img_name="Fig_1.png"):
```suggestion
    def __init__(self, camera_id=0, img_name="Fig_1.jpeg"):
```
修正用で出しておきます。

2024-08-05 10:31 UTC, YKhm20020 commented on front_camera/Makefile
> +    SAVE_NAME = Fig_1.png # デフォルト値
```suggestion
    SAVE_NAME = Fig_1.jpeg # デフォルト値
```
修正用で出しておきます

2024-08-05 10:31 UTC, YKhm20020 commented on front_camera/front_camera/camera_interface.py
> +        file_name = datetime.now().strftime("%Y-%m-%d_%H-%M-%S") + ".png"
```suggestion
        file_name = datetime.now().strftime("%Y-%m-%d_%H-%M-%S") + ".jpeg"
```
修正用で出しておきます

2024-08-06 03:59 UTC, bizyutyu commented on front_camera/front_camera/camera_interface.py
> +    def __init__(self, camera_id=0, data_format: str = "RGB888", size: Tuple[int, int] = (1640, 1232)) -> None:
(このページ)[https://zenn.dev/karaage0703/articles/96013d71ab764c]

2024-08-06 08:37 UTC, KakinokiKanta approved these changes
LGTM!

2024-08-06 08:40 UTC, negiuniv approved these changes
LGTM

2024-08-07 04:35 UTC, YKhm20020 approved these changes
Approve出してませんでした。LGTMです。
![203025](https://github.com/user-attachments/assets/e8910ac1-eb3f-453a-b1ed-5291ff7ef898)

2024-08-07 04:35 UTC, merged