close #ticket-KLI-165 走行ログ可視化のための実装
KatLab-MiyazakiUniv/etrobocon2024 pull request #31
Opened 2024-08-09 04:12 UTC by bizyutyu

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点

# 動作テスト

## 実験方法

## 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

## 実験結果

## 添付資料

2024-09-03 20:29 UTC, aridome222 requested changes
命名で細かい点が1つだけ。

2024-09-03 20:29 UTC, aridome222 commented on module/common/RunLogger.h
> +  void addTolog(int _Brightness, int _RightPwm, int _leftPwm, int _r, int _g, int _b);
```suggestion
  void addToLogs(int _Brightness, int _RightPwm, int _leftPwm, int _r, int _g, int _b);
```

2024-09-03 20:29 UTC, aridome222 commented on module/common/RunLogger.cpp
> +void RunLogger::addTolog(int _Brightness, int _RightPwm, int _leftPwm, int _r, int _g, int _b)
LogにするかLogsにするかは任せます

```suggestion
void RunLogger::addToLogs(int _Brightness, int _RightPwm, int _leftPwm, int _r, int _g, int _b)
```

2024-09-03 20:29 UTC, aridome222 commented on module/common/SystemInfo.h
> +static bool shouldGetRunLog = false;
特に明確な区別がなければ、LogかLogsに統一した方がいいかな。

```suggestion
static bool shouldGetRunLogs = false;
```

2024-09-04 00:03 UTC, YKhm20020 requested changes
いくつか変更お願いしたいところあります🐹

2024-09-04 00:03 UTC, molpui0726 commented on module/Motion/LineTracing.cpp
> +  int count = 0;
できればなんのカウントかわかるニュアンスを変数名に入れてほしいです🙏

2024-09-04 00:03 UTC, molpui0726 commented on module/EtRobocon2024.cpp
> +  if(shouldGetRunLog == true) {
```suggestion
  if(shouldGetRunLog) {
```
下のと合わせるならこう？　上と下どっちに合わせるかは任せます。

2024-09-04 00:03 UTC, molpui0726 commented on module/Motion/Straight.cpp
> +  int count = 0;
ここも変数名を明確にお願いします🙏

2024-09-04 00:03 UTC, molpui0726 commented on module/common/RunLogger.cpp
> +void RunLogger::addTolog(int _Brightness, int _RightPwm, int _leftPwm, int _r, int _g, int _b)
有留くんに対してではないけども同じところなのでここに。
_RightPwm と _leftPwm でアッパーキャメルとローワーキャメルが混ざってるので統一をお願いします。

2024-09-04 00:03 UTC, molpui0726 commented on module/common/RunLogger.h
> +   * @param Brightness
docstringの引数足りてないので、更新をお願いします。

2024-09-04 02:08 UTC, KakinokiKanta approved these changes
上2人のに対応してくれれば、後は大丈夫そう
![LGTM](https://image.lgtmoon.dev/201391)

2024-09-04 02:09 UTC, keiya121 commented on module/common/RunLogger.h
> +  void addTolog(int _Brightness, int _RightPwm, int _leftPwm, int _r, int _g, int _b);
レビューありがとうございます。addToLogsに変更しました。

2024-09-04 02:09 UTC, keiya121 commented on module/common/SystemInfo.h
> +static bool shouldGetRunLog = false;
RunLogsに統一しました。ありがとうございます。

2024-09-04 02:10 UTC, keiya121 commented on module/EtRobocon2024.cpp
> +  if(shouldGetRunLog == true) {
レビューありがとうございます。下の記法に統一しました。

2024-09-04 02:11 UTC, keiya121 commented on module/common/RunLogger.h
> +   * @param Brightness
ありがとうございます。docstring、_RightPwm と _leftPwmの統一完了しました。

2024-09-04 02:24 UTC, keiya121 commented on module/Motion/LineTracing.cpp
> +  int count = 0;
countの変数名修正しました🙏

2024-09-04 04:33 UTC, YKhm20020 approved these changes
修正確認しました、LGTMです！
![LGTMoon 101481](https://github.com/user-attachments/assets/b834fe23-4e84-469d-be40-03be0703600b)

2024-09-06 07:21 UTC, aridome222 approved these changes
修正お疲れ様！LGTM!

2024-09-08 05:25 UTC, merged