close #KLI-163 コース復帰動作の実装
KatLab-MiyazakiUniv/etrobocon2024 pull request #32
Opened 2024-08-11 15:37 UTC by CHIHAYATAKU

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点

- LineTracing.cpp,h，DistanceLineTracing.cpp,h，ColorLineTracing.cpp,hにコース復帰動作のためのメソッドとコンストラクタを追加した．
- MotionParser.cpp内のDL，CLコマンド処理において引数の違いによりコンストラクタを識別できるようにした．
- DistanceLineTracingTest.cpp，ColorLineTracingTest.cppにコース復帰動作をしないときのテストケースを追加した．
→緑を7回連続で検知する乱数シードが見つけられていない．テストにおいて目標距離を大きくすると見つかるが，現実的な数値でないため不適切かもしれない．
緑連続３回の時に復帰動作が作動したが，テストは問題なく通った．

# 動作テスト
- 緑を検知して，モーションパーサー経由で復帰動作が行えることは確認できた．
- しかし，復帰動作にどういう動作をすれば上手く黒線に乗れるかがまだ確認できていない．
- 復帰動作の後に，コマンド動作を正常に再開できるかの確認もできていないため，今後の調整中での確認が必要．

2024-08-15 10:02 UTC, aridome222 approved these changes
LGTM!

2024-08-16 10:55 UTC, YKhm20020 requested changes
1個だけ小さいのがあるのでお願いします。

2024-08-16 10:55 UTC, molpui0726 commented on module/Motion/LineTracing.cpp
> +    }
```suggestion
    if(isRecoveryEnabled && isErrorState()) {
      recover();
    }
```
ここはひとつにまとめられそう。

2024-08-16 11:28 UTC, CHIHAYATAKU commented on module/Motion/LineTracing.cpp
> +    }
修正しました．

2024-09-02 07:39 UTC, closed without merging