close #KLI-173 物体検出を行う
KatLab-MiyazakiUniv/etrobocon2024 pull request #37
Opened 2024-09-01 16:15 UTC by takahashitom

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
- 無線通信デバイスのサーバーに画像をアップロードし、その画像に対する物体検出の結果を受け取るコマンドをMakefileに追加
  - make upload_detect

# 動作テスト

## 実験方法

## 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

## 実験結果

## 添付資料

2024-09-04 09:00 UTC, bizyutyu requested changes

2024-09-04 09:00 UTC, bizyutyu commented on Makefile
> +	curl -X POST -F "file=@"$(FILE_PATH)"" $(SERVER_URL)/detect -OJ
冗長さ軽減。
```suggestion
upload_detect: flag_delete
	curl -X POST -F "file=@"$(FILE_PATH)"" $(SERVER_URL)/detect -OJ
```

2024-09-04 09:17 UTC, bizyutyu approved these changes
LGTM！！
![LGTM](https://image.lgtmoon.dev/264748)

2024-09-06 08:34 UTC, CHIHAYATAKU commented
authorにtakahashitom追記でお願いします．コメントだけ残しておきます．

2024-09-18 04:53 UTC, closed without merging