#KLI-23 PIDを計算する
KatLab-MiyazakiUniv/etrobocon2024 pull request #4
Opened 2024-05-29 07:57 UTC by CHIHAYATAKU

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
etrobocon2024/moduleの直下にCalculatorフォルダ(etrobocon2024/module/Calculator/)を作成し，
そこに以下の2つのファイルを追加．

- Pid.cpp

- Pid.h

etrobocon2024/testに以下のファイルを追加．

- PidTest.cpp

# 動作テスト
PidTest.cppのテストに通りました．

## 参考資料
2022年度のPID制御プログラムです．2024年版のPID計算の処理は2022年版と変えていません．
[Pid.cpp](https://github.com/KatLab-MiyazakiUniv/etrobocon2022/blob/main/module/Calculator/Pid.cpp)
[Pid.h](https://github.com/KatLab-MiyazakiUniv/etrobocon2022/blob/main/module/Calculator/Pid.h)
[PidTest.cpp](https://github.com/KatLab-MiyazakiUniv/etrobocon2022/blob/main/test/PidTest.cpp)

2024-06-03 06:30 UTC, KakinokiKanta requested changes
テストに関しては、今までこれで通ってきたし問題なかったから別に良いかな～とも思ってるんだけど、変更した方が良いかは他の人たちの意見も聞きたい。

2024-06-03 06:30 UTC, KakinokiKanta commented on module/Calculator/Pid.cpp
> + * @file Pid.cpp
結局この項目は残すってことになったんだっけ？
個人的には、VSCode内でファイル名を検索するときに、プロジェクト内の文字列検索と同じショートカットキーが使えるから、残したい派なんだけど...
ここで聞くことじゃないかもだけど

2024-06-03 06:30 UTC, KakinokiKanta commented on module/Calculator/Pid.h
> +   * @fn void setPidGain(double _kp, double _ki, double _kd);
```suggestion
```
この項目いるかな？
個人的には要らないと思うんだけど、他の人の意見も聞きたい

2024-06-03 06:30 UTC, KakinokiKanta commented on module/Calculator/Pid.h
> +   * @fn double calculatePid(double currentValue, double delta = 0.01);
```suggestion
```
ここも

2024-06-03 06:30 UTC, KakinokiKanta commented on test/PidTest.cpp
> +    double expected = p + i + d;
```suggestion
    double expected = 実際に上記パラメータで算出される操作量;
```
みたいにしないと意味なくない？
現状、テスト対象のクラスと同じことを再度やってるだけな気がする。
`実際に上記パラメータで算出される操作量`の部分は手元で計算した値を入れないといけないんだけど、細かい数値がですぎて、無理かな？

2024-06-03 06:30 UTC, KakinokiKanta commented on test/PidTest.cpp
> +    double expected = p + i + d;
ここも

2024-06-03 06:30 UTC, KakinokiKanta commented on test/PidTest.cpp
> +    double expected = p + i + d;
ここも

2024-06-03 06:30 UTC, KakinokiKanta commented on test/PidTest.cpp
> +    double expected = p + i + d;
ここも

2024-06-03 06:30 UTC, KakinokiKanta commented on test/PidTest.cpp
> +    double expected = p + i + d;
ここも

2024-06-03 06:30 UTC, KakinokiKanta commented on test/PidTest.cpp
> +    double expected = p + i + d;
ここも

2024-06-03 06:30 UTC, KakinokiKanta commented on test/PidTest.cpp
> +    double expected = p + i + d;
ここも

2024-06-03 06:30 UTC, KakinokiKanta commented on test/PidTest.cpp
> +    expected = p + i + d;
ここも

2024-06-03 06:30 UTC, KakinokiKanta commented on test/PidTest.cpp
> +    actualPid.setPidGain(expected_p, expected_i, expected_d);  // PIDゲインの更新
```suggestion
    expected_kp = 0.1;
    expected_ki = 0.2;
    expected_kd = 0.3;
    actualPid.setPidGain(expected_kp, expected_ki, expected_kd);  // PIDゲインの更新
```
にしてほしい

2024-06-03 07:31 UTC, CHIHAYATAKU commented on module/Calculator/Pid.cpp
> + * @file Pid.cpp
自分も残したいです．

2024-06-03 07:31 UTC, CHIHAYATAKU commented on module/Calculator/Pid.h
> +   * @fn void setPidGain(double _kp, double _ki, double _kd);
これは2022年から持ってきてほぼそのままなので残ったままでした．
2023年の方は無いようですし，無くても分かるので自分も要らないと思います．

2024-06-03 07:31 UTC, CHIHAYATAKU commented on test/PidTest.cpp
> +    actualPid.setPidGain(expected_p, expected_i, expected_d);  // PIDゲインの更新
test/PidTest.cpp内のexpected_p，expected_i，expected_dをexpected_kp，expected_ki，expected_kdにするということで合っていますか?

2024-06-03 07:48 UTC, CHIHAYATAKU commented on test/PidTest.cpp
> +    double expected = p + i + d;
calculatepidが期待通りに動いてくれるかのテストなので，個人的には手元でしても同じ計算過程になるなら，このままでよいと思うのですが．．
理解できているか不安なので自分も他の方の意見も聞きたいです．

2024-06-03 10:00 UTC, YKhm20020 requested changes
いくつか計算と、author の書き直しだけお願いします🙇‍♂️

2024-06-03 10:00 UTC, molpui0726 commented on module/Calculator/Pid.cpp
> + * @file Pid.cpp
残す方針にしたと思います。
author 欄の修正だけ忘れないようお願いします🙇‍♂️

2024-06-03 10:00 UTC, molpui0726 commented on module/Calculator/Pid.cpp
> + * @author TakumaChihaya
```suggestion
 * @author CHIHAYATAKU
```

前年は本名ではなくGitHubでの名前に統一してたと思うので、細かいですがこのようにお願いします🙇‍♂️

2024-06-03 10:00 UTC, molpui0726 commented on module/Calculator/Pid.h
> + * @author TakumaChihaya
```suggestion
 * @author CHIHAYATAKU
```
ここもお願いします🙇‍♂️

2024-06-03 10:00 UTC, molpui0726 commented on module/Calculator/Pid.h
> +   * @fn void setPidGain(double _kp, double _ki, double _kd);
前年はなかったと記憶しています。
特に困ったこともなく、他の関数についても記述が必要になるので、なしの方で統一してもいいと個人的に思っています。

2024-06-03 10:00 UTC, molpui0726 commented on test/PidTest.cpp
> +    double expected = p + i + d;
テストを正しく実行するという意味では柿木さんの指摘のようにすべきだとは思います。
プログラムの処理が手元と同じ計算になるかどうかをチェックするのがテストで、それが正しい前提にするのはテストの意味が怪しくなる気もします。
前年になおせていなくて申し訳ないですが、コメントで計算過程を記して操作量を初期化して、その値と比較した方がいい派です。
他の方の意見お待ちしております🙇‍♂️

2024-06-03 10:00 UTC, YKhm20020 commented on test/PidTest.cpp
> + * @author TakumaChihaya
```suggestion
 * @author CHIHAYATAKU
```
ここもお願いします🙇‍♂️

2024-06-03 13:37 UTC, CHIHAYATAKU commented on module/Calculator/Pid.cpp
> + * @author TakumaChihaya
すみません。直した気になってました🙇

2024-06-03 13:46 UTC, KakinokiKanta commented on module/Calculator/Pid.cpp
> + * @file Pid.cpp
OK！

2024-06-03 13:48 UTC, CHIHAYATAKU commented on test/PidTest.cpp
> +    double expected = p + i + d;
確かに、手元の計算と同じになるのかのチェックがテストですね。手元で計算したものも作っておきます。

2024-06-03 13:54 UTC, KakinokiKanta commented on test/PidTest.cpp
> +    actualPid.setPidGain(expected_p, expected_i, expected_d);  // PIDゲインの更新
そうそう
ロボコンのコードだと、PID制御における操作量を`p``i``d`っておいてて、ゲインはkp、ki、kdってしてるから。
実際には、今`p`とかってしてる変数が実際には`expected_p`になると思うし、今`expected_p`とかってなってるやつらって、実際にはP値

2024-06-03 13:59 UTC, KakinokiKanta commented on test/PidTest.cpp
> +    actualPid.setPidGain(expected_p, expected_i, expected_d);  // PIDゲインの更新
```suggestion
    kp = 0.1;
    ki = 0.2;
    kd = 0.3;
    actualPid.setPidGain(kp, ki, kd);  // PIDゲインの更新
```
だからだね

2024-06-03 14:02 UTC, CHIHAYATAKU commented on test/PidTest.cpp
> +    actualPid.setPidGain(expected_p, expected_i, expected_d);  // PIDゲインの更新
了解です🫡

2024-06-03 17:42 UTC, bizyutyu reviewed
個人的に気になるところ、みんなの意見聞きたいのでコメントにしときます。

2024-06-03 17:42 UTC, bizyutyu commented on module/Calculator/Pid.cpp
> +PidGain::PidGain(double _kp, double _ki, double _kd) : kp(_kp), ki(_ki), kd(_kd) {}
個人的に、各ゲインkp, ki, kdについて、負の数を取れなくしたいけど、他の人の意見も聞きたい。
変えるならこんな感じ、
```
PidGain::PidGain(double _kp, double _ki, double _kd)
: kp(_kp < 0 ? 0 : _kp), ki(_ki < 0 ? 0 : _ki), kd(_kd < 0 ? 0 : _kd) {}
```

2024-06-03 17:42 UTC, bizyutyu commented on module/Calculator/Pid.cpp
> +  pidGain.kd = _kd;
変えるならこっちも
ちなみに、テストのkp,ki,kdにマイナス入れてるやつが通らなくなると思います。
```
pidGain.kp = _kp < 0 ? 0 : _kp;
pidGain.ki = _ki < 0 ? 0 : _ki;
pidGain.kd = _kd < 0 ? 0 : _kd;
```

2024-06-03 18:32 UTC, KakinokiKanta commented on module/Calculator/Pid.cpp
> +PidGain::PidGain(double _kp, double _ki, double _kd) : kp(_kp), ki(_ki), kd(_kd) {}
負の値は取れなくして良い気がする。操作量が負の値になる可能性があるのっておかしいし

2024-06-04 05:52 UTC, CHIHAYATAKU commented on module/Calculator/Pid.cpp
> +  pidGain.kd = _kd;
分かりました．変更しておきます．

2024-06-04 07:07 UTC, CHIHAYATAKU commented on test/PidTest.cpp
> +    actualPid.setPidGain(expected_p, expected_i, expected_d);  // PIDゲインの更新
今気づいたのですが、コーディング規約にテストではexpectedとactualを比較しているかという項目があったのでexpectedを付けてたように思えます。
kpkikpはそれぞれ柿木さんがおっしゃったように宣言して、実際に比較する変数expected_*=*を別に作る方向でいこうと思うのですがいいですか？下のような感じです．
```
    double kp = 0.1;
    double ki = 0.03;
    double kd = 0.612;
    PidGain actualPidGain(kp, ki, kd);
    double expected_kp = kp;
    double expected_ki = ki;
    double expected_kd = kd;
    EXPECT_DOUBLE_EQ(expected_kp, actualPidGain.kp);
    EXPECT_DOUBLE_EQ(expected_ki, actualPidGain.ki);
    EXPECT_DOUBLE_EQ(expected_kd, actualPidGain.kd);
```

2024-06-04 07:34 UTC, CHIHAYATAKU commented on test/PidTest.cpp
> +    double expected = p + i + d;
テストが手元での計算結果でも通りました．
なのですが，やはり正しい計算過程で改めて計算したexpectedと，calculatePidで計算したactualを比較してcalculatePidが正しく機能しているかをテストするという，テストでの処理(?)は変わらないので手元で同じ計算をしても機械に任せてもどっちでも同じことをしていると思います．また，実際に本番で計算するのは機械ですし，改めて正しい計算過程を与えて計算された結果をexpectedとした方が正しくテストできていると言えると個人的に感じます．
あくまでもテスト経験0の個人的な意見なので，いくらでも異議受け付けます🙇‍♂️

2024-06-04 10:53 UTC, KakinokiKanta commented on test/PidTest.cpp
> +    actualPid.setPidGain(expected_p, expected_i, expected_d);  // PIDゲインの更新
いいね！

2024-06-04 12:21 UTC, aridome222 commented on test/PidTest.cpp
> +    double expected = p + i + d;
手計算のミスを減らすという点なら良いと思うけれど、
宅間君の考え方だと、calculatePidの実装が間違っていてもexpectedとactualが同じになるよね。
手元で同じ計算をしても機械に任せてもどっちでも同じになるっていうのは、結果論だと思う。
実装と手計算の考え方(計算過程)が同じでも、実装の部分で間違ってる可能性が万が一にもあると思うから、
僕の意見としては、木村君が述べたように、コメントで計算過程を記して操作量を初期化して、その値と比較した方がいいと思う。

2024-06-04 12:31 UTC, bizyutyu requested changes
Request changesに変更するためのコメントです。

2024-06-04 13:15 UTC, bizyutyu approved these changes
テスト通れば、問題ないかと思います。LGTM！
![LGTM](https://image.lgtmoon.dev/249782)

2024-06-04 13:23 UTC, bizyutyu requested changes
Approve間違えました。恥ずかしいけど、再びRequest changes！！
![image](https://github.com/KatLab-MiyazakiUniv/etrobocon2024/assets/132331737/5e46d1a0-1b5d-4334-aa50-a3adda4572e3)

2024-06-04 13:55 UTC, CHIHAYATAKU commented on test/PidTest.cpp
> +    double expected = p + i + d;
すみません、言葉不足でした。僕の考えではcalculatePidの処理は意識せず、改めて定義に戻って計算処理を記述して、その結果値をexpectedにするなら機械に計算させてもいいのではという考えでした。

2024-06-04 14:43 UTC, aridome222 commented on test/PidTest.cpp
> +    double expected = p + i + d;
なるほど、手計算を機械に計算させるってことね。
それは良さそう！手計算のミス減らせるし、楽できるし良いね！

2024-06-04 15:14 UTC, CHIHAYATAKU commented on test/PidTest.cpp
> +    double expected = p + i + d;
[ネットのPID制御プログラム例](https://controlabo.com/pid-program/#toc2)での積分処理では，katlabのコードに置き換えると，
`integral += (currentDeviation + prevDeviation) * delta/2;`
となっていて，現在のkatlabの処理は
` integral += currentDeviation * delta;`
となっています．
実際に計算すると，0.004~0.005ほどの誤差が出たのですが，どうしますか？例えば，kp = 0.6，ki = 0.02，kd = 0.03の時，現在は"180.00999999999999"で，変更すると"180.005"になります．

2024-06-04 16:57 UTC, CHIHAYATAKU commented
テストのexpectedは手計算の結果を使うように変更しました．
また，いろいろ調べた結果，積分処理は2023年と同様，
`integral += (currentDeviation + prevDeviation) * delta / 2;`
に変更しました．
ギリギリで申し訳ありませんが，レビューお願いします🙇‍♂️

2024-06-05 01:23 UTC, bizyutyu approved these changes
修正お疲れ様。LGTM!!
![LGTM](https://image.lgtmoon.dev/84535)

2024-06-05 08:31 UTC, KakinokiKanta approved these changes
![LGTM](https://image.lgtmoon.dev/249935)

2024-06-05 10:25 UTC, YKhm20020 approved these changes
遅れてしまってごめんなさい、LGTMです！
![247315 400x380](https://github.com/KatLab-MiyazakiUniv/etrobocon2024/assets/128010507/bb243607-e461-4137-aee5-9d34035bf1cd)

2024-06-05 11:33 UTC, merged