close #KLI-178 BCの撮影箇所連結機能の実装
KatLab-MiyazakiUniv/etrobocon2024 pull request #40
Opened 2024-09-03 07:50 UTC by KakinokiKanta

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
- 配置エリアBの前半、後半、配置エリアAでのコマンドファイルを連結して、ダブルループエリアのコマンドファイルを生成するshファイルを追加
- 上記ファイルを `make double-<left of right>-<0~5の撮影候補箇所>` で実行できるようMakefileにコマンド追加
- 各コマンドファイルのサンプルを追加

## 添付資料
[Notionリンク](https://www.notion.so/uom-katlab/BC-897f6fad1c79423c9c98090f4113535e)

2024-09-03 20:05 UTC, aridome222 approved these changes
見た感じ問題なさそうです。
![LGTM](https://image.lgtmoon.dev/2607)

2024-09-03 23:43 UTC, YKhm20020 approved these changes
確認しました！　LGTMです、お疲れ様でした🙇‍♂️
![LGTMoon 184523](https://github.com/user-attachments/assets/ab00b273-eece-42bb-b3dd-12433129daa7)

2024-09-04 02:46 UTC, keiya121 approved these changes
良さそうです！お忙しい中ありがとうございました。

![ソニックLGTM](https://github.com/user-attachments/assets/87ab2cb0-b4eb-4ef3-943e-087a4f4ef475)

2024-09-04 08:21 UTC, bizyutyu requested changes
前半を0\~3にして後半を4\~5にする変更お願いします。
下記に加えて、```datafiles/datafile_parts```のファイル名も一部変更必要そうです。

2024-09-04 08:21 UTC, bizyutyu commented on scripts/double_loop_right_merger.sh
> +if [ "$1" -le 2 ]; then
```suggestion
if [ "$1" -le 3 ]; then
```

2024-09-04 08:21 UTC, bizyutyu commented on scripts/double_loop_left_merger.sh
> +if [ "$1" -le 2 ]; then
```suggestion
if [ "$1" -le 3 ]; then
```

2024-09-08 04:20 UTC, YKhm20020 commented on scripts/double_loop_right_merger.sh
> +if [ "$1" -le 2 ]; then
対応しました👍

2024-09-08 04:21 UTC, YKhm20020 commented on scripts/double_loop_left_merger.sh
> +if [ "$1" -le 2 ]; then
こちらも同様に対応いたしました👍

2024-09-08 05:42 UTC, bizyutyu approved these changes
LGTM
![LGTM](https://image.lgtmoon.dev/178684)

2024-09-08 05:43 UTC, merged