close #ticket-KLI-194 配置エリアBでの撮影動作実装
KatLab-MiyazakiUniv/etrobocon2024 pull request #41
Opened 2024-09-06 08:29 UTC by bizyutyu

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
- 背景の黄色検出をクラスとして分離

# 動作テスト

## 添付資料

2024-09-06 08:55 UTC, CHIHAYATAKU requested changes

2024-09-06 08:55 UTC, CHIHAYATAKU commented on front_camera/front_camera/yellow_rectangle_detecter.py
> +class YellowRectangleDetecter:
detecter ->detecorですかね？
```suggestion
class YellowRectangleDetector:
```

2024-09-06 09:06 UTC, YKhm20020 commented on front_camera/front_camera/yellow_rectangle_detecter.py
> +class YellowRectangleDetecter:
修正しました、早期発見ありがとう🙏

2024-09-11 05:58 UTC, YKhm20020 requested changes
いくつかあるのでお願いします🙏

2024-09-11 05:58 UTC, YKhm20020 commented on module/Motion/AreaBCameraAction.cpp
> +    snprintf(buf, LARGE_BUF_SIZE, "The preTargetAngle value passed to preRotation is %d",
```suggestion
    snprintf(buf, LARGE_BUF_SIZE, "The preTargetAngle value passed to preRotation is 0",
```
変えるならこう？　上と全く同じ文でいいなら、preTargetAngle <= 0 でもいいと思う。

2024-09-11 05:58 UTC, YKhm20020 commented on module/Motion/AreaBCameraAction.cpp
> +    snprintf(buf, LARGE_BUF_SIZE, "The postTargetAngle value passed to postRotation is %d",
ここも

2024-09-11 05:58 UTC, YKhm20020 commented on module/Motion/AreaBCameraAction.cpp
> +    snprintf(buf, LARGE_BUF_SIZE, "The postTargetAngle value passed to postRotation is %d",
```suggestion
    snprintf(buf, LARGE_BUF_SIZE, "The postTargetAngle value passed to postRotation is 0",
```
ここも

2024-09-11 05:58 UTC, YKhm20020 commented on front_camera/front_camera/get_correction_angle.py
> +    print(f"{angle_int}")
```suggestion
    print(angle_int)
```
文字列中に変数入れなくていいならf記法じゃなくていいかな

2024-09-11 05:58 UTC, YKhm20020 commented on front_camera/front_camera/get_correction_angle.py
> +        # 画像を読み込む
docstringだけお願い🙏

2024-09-11 05:58 UTC, YKhm20020 commented on module/Motion/AreaBCameraAction.cpp
> +  snprintf(buf, LARGE_BUF_SIZE, "Run AreaBCameraAction ()");
ここのメッセージに変数の値がほしいかも

2024-09-11 06:23 UTC, KakinokiKanta approved these changes
![LGTM](https://image.lgtmoon.dev/241018)

2024-09-11 06:33 UTC, keiya121 commented on module/Motion/AreaBCameraAction.cpp
> +  snprintf(buf, LARGE_BUF_SIZE, "Run AreaBCameraAction ()");
対応完了しました🙏

2024-09-11 06:54 UTC, takahashitom approved these changes
お疲れ様です。

2024-09-11 06:54 UTC, takahashitom commented on module/Motion/CorrectingRotation.cpp
> +#include <string.h>
```suggestion
```
loggerの方でインクルードされてるので必要ないかも？です

2024-09-11 09:16 UTC, bizyutyu commented on module/Motion/CorrectingRotation.cpp
> +#include <string.h>
修正しました！

2024-09-18 04:53 UTC, CHIHAYATAKU approved these changes
![LGTM](https://image.lgtmoon.dev/265855)

2024-09-18 04:59 UTC, YKhm20020 approved these changes
Approveにし忘れていたみたいです、ごめんなさい。

2024-09-18 06:03 UTC, merged