close #KLI-217 スマートキャリー実装
KatLab-MiyazakiUniv/etrobocon2024 pull request #44
Opened 2024-11-01 08:56 UTC by CHIHAYATAKU

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
- コマンドcsvファイルに地区大会時点の内容を反映
- 角度補正回頭を色を指定できるように拡張
  - `front_camera/Makefile`の`correction-angle`コマンドのオプションで色を受け取るように変更
  - `front_camera/front_camera/yellow_rectangle_detector.py`を`front_camera/front_camera/color_rectangle_detector.py`に変更し、他の色に対応できるように変更
- その他、`color_rectangle_detector.py`に対応するように処理を変更
  - `module/MotionParser.cpp`
  - `module/Motion/CorrectingRotation.h`
  - `module/Motion/CorrectingRotation.cpp`
  - `module/Motion/AreaBCameraAction.h`
  - `module/Motion/AreaBCameraAction.cpp`
  - `front_camera/front_camera/get_correction_angle.py`
  - `front_camera/front_camera/frame_timing_calculator.py`
- `test/AreaMasterTest.cpp`のスマートキャリーRunのテストで、シェルからコマンド実行するとその先のテストに進めないため、一旦コメントアウト

# 動作テスト
https://www.notion.so/uom-katlab/126dd5b1cc1880ba9491dc65ced36c9e?pvs=4#131dd5b1cc18806fb4dcf0a0eeb10691

## 添付資料
https://www.notion.so/uom-katlab/126dd5b1cc1880ba9491dc65ced36c9e?pvs=4

2024-11-03 09:16 UTC, YKhm20020 requested changes
レビュー遅くなりました、すみません🙇‍♂️
いくつか見ていただきたいところがあるので、お願いします🙏

2024-11-03 09:16 UTC, molpui0726 commented on front_camera/front_camera/color_rectangle_detector.py
> +        return None
ここは None で返ることなさそう？

2024-11-03 09:16 UTC, YKhm20020 commented on front_camera/front_camera/color_rectangle_detector.py
> +        """
```suggestion
    def detect_rectangle(self, frame) -> float:
        """対象色の矩形を検出する。
        Args:
            frame (numpy.ndarray): 処理対象の画像データ
        Returns:
            float: 検出した矩形の面積
        """
```
None が返らないならこんな感じになりそう。書き方間違ってたらごめんなさい。

2024-11-03 09:16 UTC, YKhm20020 commented on front_camera/front_camera/color_rectangle_detector.py
> +            raise ValueError(f"{color}は定義されていません。定義されている色: {list(self.COLOR_BOUNDS.keys())}")
これってエラー正しく出る？
辞書型の変数をリスト化してキーを出力してるけど、リストからキーって取ってこれたっけ。
辞書型なら取れそう。ちゃんとエラー出てるなら大丈夫です🙆

2024-11-04 03:23 UTC, takahashitom commented on front_camera/front_camera/color_rectangle_detector.py
> +        return None
レビューありがとうございます。
ここは、輪郭が見つからなかった時にNoneで返るようになってるはずです。
具体的には、74行目か80行目のif文でfalseった時にここに行き着くはずです。

2024-11-04 03:25 UTC, takahashitom commented on front_camera/front_camera/color_rectangle_detector.py
> +            raise ValueError(f"{color}は定義されていません。定義されている色: {list(self.COLOR_BOUNDS.keys())}")
試してみたらエラー出ました。
問題なさそうです。
![スクリーンショット 2024-11-04 121330](https://github.com/user-attachments/assets/64fd0d1a-d0d9-4422-a5ec-def34d887085)

2024-11-05 04:10 UTC, keiya121 requested changes

2024-11-05 04:10 UTC, ghost commented on front_camera/front_camera/frame_timing_calculator.py
> +        self.yellow_rectangle_detector = ColorRectangleDetector("yellow")
ここのyellowが小文字になってるけどちゃんと動きそう？
```suggestion
        self.yellow_rectangle_detector = ColorRectangleDetector('YELLOW')
```

2024-11-05 04:10 UTC, keiya121 commented on front_camera/work/RasPike
この変更って外せますか？🙏

2024-11-05 04:10 UTC, keiya121 commented on work/RasPike
出来ればここもお願いしたいです。

2024-11-05 04:11 UTC, keiya121 requested changes

2024-11-05 04:11 UTC, keiya121 commented on module/Motion/CorrectingRotation.cpp
> + * @author bizyutyu CHIHAYATAKU takahashitpom
細かいけど
```suggestion
 * @author bizyutyu CHIHAYATAKU takahashitom
```

2024-11-05 04:54 UTC, bizyutyu requested changes
よろしくお願いします。

2024-11-05 04:54 UTC, bizyutyu commented on front_camera/front_camera/get_correction_angle.py
> +    parser.add_argument("--color", type=str, default="yellow", help="検出する矩形の色を指定する")
大文字？
```suggestion
    parser.add_argument("--color", type=str, default="YELLOW", help="検出する矩形の色を指定する")
```

2024-11-05 04:54 UTC, bizyutyu commented on front_camera/front_camera/color_rectangle_detector.py
> +@author: bizyutyu YKhm20020 CHIHAYATAKU
他のところも書いて良い？
```suggestion
@author: bizyutyu YKhm20020 CHIHAYATAKU takahashitom
```

2024-11-05 04:54 UTC, bizyutyu commented on front_camera/front_camera/get_correction_angle.py
> +        self.rectangle_detector = ColorRectangleDetector(color)
ColorRectamgleDetectorの例外処理
```suggestion
        try:
            self.rectangle_detector = ColorRectangleDetector(color)
        except ValueError as e:
            print(e)
```

2024-11-05 04:54 UTC, bizyutyu commented on front_camera/front_camera/frame_timing_calculator.py
> +        self.yellow_rectangle_detector = ColorRectangleDetector("yellow")
例外のキャッチ+色は大文字？（yellow→YELLOW）
```suggestion
        try:
            self.yellow_rectangle_detector = ColorRectangleDetector("YELLOW")
        except ValueError as e:
            print(e)
```

2024-11-05 04:54 UTC, bizyutyu commented on module/Motion/CorrectingRotation.h
> +   * @param _color 検出する矩形の色（"yellow" or "red"）
```suggestion
   * @param _color 検出する矩形の色（"YELLOW" or "RED"）
```

2024-11-05 04:54 UTC, bizyutyu commented on front_camera/front_camera/get_correction_angle.py
少しやりすぎかもしれないけど、カスタムエラークラスを使ってエラーハンドリングをすれば呼び出し元でエラーハンドリングしやすくなります。フツーにValueErrorとしてキャッチするだけでも十分だと言われればそのような気がする。変数名等はあまり考えずに付けてるので適宜変更お願いします。
```
class ImageLoadError(Exception):
    pass

class RectangleDetectionError(Exception):
    pass
```

2024-11-05 04:54 UTC, bizyutyu commented on front_camera/front_camera/get_correction_angle.py
> +            raise ValueError(f"{self.rectangle_detector.color}色の長方形が検出されませんでした")
カスタムエラークラスを使う場合、以下2つの変更も必要。
```suggestion
            raise RectangleDetectionError(f"{self.rectangle_detector.color}色の長方形が検出されませんでした")
```

少し上の行のraiseの部分を、
``` 
raise ImageLoadError(f"画像を読み込めませんでした: {image_path}")
```
に変更する。

2024-11-05 04:54 UTC, bizyutyu commented on front_camera/front_camera/get_correction_angle.py
> +    angle_corrector = GetCorrectionAngle(args.color)
カスタムエラークラスを使う場合の変更。
```suggestion
try:
    angle_corrector = GetCorrectionAngle(args.color)
except ImageLoadError as e:
    print(f"画像読み込みエラー: {e}")
    # 画像読み込みエラー特有の処理
except RectangleDetectionError as e:
    print(f"長方形検出エラー: {e}")
    # 長方形検出エラー特有の処理
except Exception as e:
    print(f"予期せぬエラー: {e}")
```

2024-11-05 04:57 UTC, takahashitom commented on front_camera/front_camera/color_rectangle_detector.py
> +        """
れびゅーありがとうございます
コメント追加しました。
5a0abca20b19216d2f3b5cf31a94f03d6959b749

2024-11-05 04:58 UTC, takahashitom commented on module/Motion/CorrectingRotation.cpp
> + * @author bizyutyu CHIHAYATAKU takahashitpom
れびゅーありがとうございます
修正いたしました
5a0abca20b19216d2f3b5cf31a94f03d6959b749

2024-11-05 05:01 UTC, takahashitom commented on front_camera/front_camera/color_rectangle_detector.py
> +@author: bizyutyu YKhm20020 CHIHAYATAKU
れびゅーありがとうございます
追加しました
5a0abca20b19216d2f3b5cf31a94f03d6959b749

2024-11-05 05:44 UTC, bizyutyu requested changes
少し追加です。
カスタムエラー関連の変更点については、やらなくても大丈夫です。

2024-11-05 05:44 UTC, bizyutyu commented on front_camera/front_camera/get_correction_angle.py
>      angle = angle_corrector.calculate_correction_angle(save_path)
カスタムエラー使う場合の変更例。
```suggestion
try:
    angle = angle_corrector.calculate_correction_angle(save_path)
except ImageLoadError as e:
    print(f"画像読み込みエラー: {e}")
    # 画像読み込みエラー特有の処理
except RectangleDetectionError as e:
    print(f"長方形検出エラー: {e}")
    # 長方形検出エラー特有の処理
except Exception as e:
    print(f"予期せぬエラー: {e}")
```

2024-11-05 05:55 UTC, takahashitom commented on front_camera/front_camera/frame_timing_calculator.py
> +        self.yellow_rectangle_detector = ColorRectangleDetector("yellow")
動かなそうです。
修正しました。ありがとうございます。
d327dc26c8be00225481d57daaad2ca48e5deb00

2024-11-05 05:55 UTC, takahashitom commented on front_camera/front_camera/get_correction_angle.py
> +    parser.add_argument("--color", type=str, default="yellow", help="検出する矩形の色を指定する")
ありがとうございます。
修正しました。
d327dc26c8be00225481d57daaad2ca48e5deb00

2024-11-05 05:56 UTC, takahashitom commented on module/Motion/CorrectingRotation.h
> +   * @param _color 検出する矩形の色（"yellow" or "red"）
修正しました。
ありがとうございます。
d327dc26c8be00225481d57daaad2ca48e5deb00

2024-11-06 02:35 UTC, YKhm20020 commented on front_camera/front_camera/color_rectangle_detector.py
> +            raise ValueError(f"{color}は定義されていません。定義されている色: {list(self.COLOR_BOUNDS.keys())}")
なるほど、辞書のキーを取ってきて、それをリスト化して表示してましたか。
勘違いしてました、ありがとう！😊

2024-11-06 02:36 UTC, YKhm20020 approved these changes
自分が聞いたところは全部答えてもらえたので、先にLGTM出しておきます！
![214057](https://github.com/user-attachments/assets/83736042-2cdf-4fed-b1c0-0bf46929147d)

2024-11-06 08:15 UTC, keiya121 approved these changes
gitignoreにまで入れていただいてありがとうございます

![LGTM](https://image.lgtmoon.dev/274485)

2024-11-06 08:54 UTC, bizyutyu approved these changes
LGTM!
![LGTM](https://image.lgtmoon.dev/116193)

2024-11-07 11:32 UTC, merged