close KLI-212 タイムアウトの原因調査・改善
KatLab-MiyazakiUniv/etrobocon2024 pull request #45
Opened 2024-11-06 07:40 UTC by takahashitom

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
- module/Calibrator.cpp を変更
    - waitForStart() 関数で１分間物体を認識しなかったら false を返すようにした。
    - measurerを関数ごとにインスタンス化し、関数の終わりで明示的にインスタンスを消去するようにした。
- module/EtRobocon2024.cpp で waitForStart() から false を受け取ったら再び waitForStart() を呼び出すように変更した。

# 動作テスト
- センサーの値が固定されたり、処理がタイムアウトしたりしなくなった。
    - 検証に一回10分かかる以上、検証回数が少ないです。（完全に解決できたとは言いたくない）
- 実行するごとに spike を再起動するようにすると、10分で処理が止まった。

## 添付資料

2024-11-09 08:59 UTC, YKhm20020 approved these changes
お疲れ様です、LGTM出します！
センサー反応しないときはボタンも反応しないらしいので、緊急時のボタン発進は諦めかもです。
![LGTMoon 208510](https://github.com/user-attachments/assets/df2bf989-8f7a-430d-915a-5f6859e1ae4a)

2024-11-09 10:07 UTC, aridome222 approved these changes
5分以内にフリーズしなくなったのなら、この実装で良さそう。
お疲れ様、LGTM!
![LGTM](https://image.lgtmoon.dev/10141)

2024-11-09 14:26 UTC, bizyutyu commented on module/Calibrator.cpp
> +  // 1分毎にMeasurerインスタンスを再生する
生成か再生成？
```suggestion
  // 1分毎にMeasurerインスタンスを生成する
```

2024-11-09 14:43 UTC, bizyutyu requested changes

2024-11-09 14:43 UTC, bizyutyu commented on module/Calibrator.cpp
> +      Measurer* measurer = new Measurer();
deleteはポインタが指すメモリ領域を解放するだけで、ポインタ変数自体は消えないみたいなので、再代入する形にした方が良いということに今更気づいた、、、
こうするなら、メンバ変数としてmeasurerを宣言できる。
```suggestion
      measurer = new Measurer();
```

2024-11-13 07:20 UTC, bizyutyu approved these changes
実機確認もしてたし、Googleテスト画面通ればOKだと思います。
![LGTM](https://image.lgtmoon.dev/185138)

2024-11-18 06:42 UTC, merged