close #KLI-26 モータを動かす
KatLab-MiyazakiUniv/etrobocon2024 pull request #5
Opened 2024-05-31 14:22 UTC by takahashitom

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
モータを動かすためのクラスを定義したファイル"Controller.h", "Controller.cpp"の追加
実機での動作確認のために必要となった、Timerクラスを定義したファイル"Timer.h", "Timer.cpp"の追加
"Timer.h", "Timer.cpp"のテストの追加
また、テストで必要となるダミー関数である"Clock.h", "Clock.cpp"の追加

# メモ
テストを行うにあたり、KLI-29でぷるリクされているファイル(Measurer＋ダミー関数)が必要なため、KLI-29のぷるリクがマージされた後に、改めてテストをプッシュする

# 動作テスト

## 添付資料

2024-06-03 09:32 UTC, YKhm20020 requested changes
細かいコメントのところだけですが、お願いします。
ちなみに、数日前はスリープが動作しないと聞きましたが、あれから動くようになりましたか？

2024-06-03 09:32 UTC, YKhm20020 commented on module/API/Controller.h
> +
```suggestion

  /**
   * コンストラクタ
   */
  Controller();

```
他のところはあるので。行頭のスペース考慮できてないので、一応修正後はclang-format通しておいてください。

2024-06-03 12:36 UTC, takahashitom commented on module/API/Controller.h
> +
レビューありがとうございます。
コメント文の追加しておきました。

スリープに関しては、<unistd.h>中のsleep()が使えなさそうだったので、Timerクラスを定義し、その中でev3apiが提供しているsleepを使用することで解決しました。

2024-06-03 18:45 UTC, KakinokiKanta requested changes
コメントの書き方を修正してほしい

2024-06-03 18:45 UTC, KakinokiKanta commented on module/API/Controller.h
> +   * タイヤのモータにPWM値をセット
```suggestion
   * @brief タイヤのモータにPWM値をセット
```
各関数の説明は、こんな感じで書いてほしい
[参考記事](https://qiita.com/inabe49/items/23e615649e8539d857a8)

2024-06-03 18:45 UTC, KakinokiKanta commented on module/API/Controller.h
> +   * タイヤのモータを停止する
```suggestion
   * @brief タイヤのモータを停止する
```
ここも

2024-06-03 18:45 UTC, KakinokiKanta commented on module/API/Controller.h
> +   * アームのモータにPWM値をセット
```suggestion
   * @brief アームのモータにPWM値をセット
```

2024-06-03 18:45 UTC, KakinokiKanta commented on module/API/Controller.h
> +   * アームのモータを停止する
```suggestion
   * @brief アームのモータを停止する
```

2024-06-03 18:45 UTC, KakinokiKanta commented on module/API/Controller.h
> +   * モータに設定するPWM値の制限
```suggestion
   * @brief モータに設定するPWM値の制限
```

2024-06-03 18:45 UTC, KakinokiKanta commented on module/API/Timer.h
> +   * 自タスクスリープ（デフォルトは10ミリ秒）
```suggestion
   * @brief 自タスクスリープ（デフォルトは10ミリ秒）
```

2024-06-03 18:45 UTC, KakinokiKanta commented on module/API/Timer.h
> +   * 走行時間を取得
```suggestion
   * @brief 走行時間を取得
```

2024-06-04 03:19 UTC, takahashitom commented on module/API/Timer.h
> +   * 走行時間を取得
レビューありがとうございます。
コメント文の修正しときました。

2024-06-04 11:10 UTC, KakinokiKanta approved these changes
![LGTM](https://image.lgtmoon.dev/249766)
テスト通ったらOKってことで！

2024-06-04 12:30 UTC, aridome222 commented on test/dummy/Clock.cpp
> +  microTime = microTime + static_cast<uint64_t>(1);
処理は変わんないけど、一応。
```suggestion
  microTime += static_cast<uint64_t>(1);
```

2024-06-04 14:27 UTC, bizyutyu approved these changes
テストが通ったら、OKなのではないかと思います。LGTM！
※アームモーターの制限やテストを追加したくもあるが、実機で競技攻略動作をしてみないことには、アームモーターの適切な最大・最小値が分からないので、今はしないほうが良いと判断しました。 ← 現状の主観です。
![LGTM](https://image.lgtmoon.dev/123676)

2024-06-04 14:38 UTC, negiuniv approved these changes
運営側の実装がちょっと難しいので、テストよう作ったと思う。
LGTM

2024-06-05 05:48 UTC, takahashitom commented on test/dummy/Clock.cpp
> +  microTime = microTime + static_cast<uint64_t>(1);
レビューありがとうございます。
たしかに、なんで上の処理だと+=にしているのに、こっちではしてないんだ？？

修正しときました。

2024-06-05 11:37 UTC, YKhm20020 approved these changes
LGTMです、お疲れ様でした！
![203025](https://github.com/KatLab-MiyazakiUniv/etrobocon2024/assets/128010507/0d1494b8-bcf5-4047-9e45-91ae078211bd)

2024-06-05 11:38 UTC, merged