close #KLI-33 GitHub Actionsにおけるclang-format実行コマンドの修正
KatLab-MiyazakiUniv/etrobocon2024 pull request #8
Opened 2024-06-02 06:03 UTC by YKhm20020

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
format-check.yaml の記法を変更。
.clang-formatファイルも合わせて空白を半角スペースに統一。
他は ticket-KLI-29と同様の変更。

## 添付資料
詳細な理由については調査したのですが、わかりませんでした。
調べたところだと、今回変更したような記法が複数のサイトから見つかっています。
https://www.turtlestoffel.com/Clang-Format , 
https://github.com/vllm-project/vllm/blob/main/.github/workflows/clang-format.yml ,
https://community.cesium.com/t/ci-cd-deployment-issues/28272

2024-06-02 17:53 UTC, aridome222 approved these changes
問題ないと思います。
![LGTM](https://image.lgtmoon.dev/117397)

2024-06-03 01:40 UTC, Negimarge approved these changes
yamlは大丈夫
指定した時のエラーどっか置いてる？

2024-06-03 03:12 UTC, YKhm20020 commented
> yamlは大丈夫 指定した時のエラーどっか置いてる？

指定したときのエラーは KLI-29 で出てるやつと同じです。

Run find ./test ./module -type f -name "*.cpp" -o -name "*.h" | xargs clang-format --dry-run --Werror *.h *.cpp
./test/dummy/Motor.h:[4](https://github.com/KatLab-MiyazakiUniv/etrobocon2024/actions/runs/9302365236/job/25602430796#step:4:5)2:16: error: code should be clang-formatted [-Wclang-format-violations]
    void stop() {};
               ^
Error: Process completed with exit code 123.

2024-06-03 05:28 UTC, KakinokiKanta reviewed
確認なんだけど、マージする時には[ticket-KLI-29](https://github.com/KatLab-MiyazakiUniv/etrobocon2024/tree/ticket-KLI-29)での変更分は入れないってことだよね？

2024-06-03 05:28 UTC, KakinokiKanta commented on module/EtRobocon2024.cpp
> +// }
これって何が変わってる？スペース無くしたとか？

2024-06-03 08:33 UTC, molpui0726 commented on module/EtRobocon2024.cpp
> +// }
確認したところ、スペースは変わっていませんでした。
赤丸のマイナスマークがファイル末尾に改行がないという意味らしいです。
clang-formatでの設定は見たところ、末尾改行に関する設定は特にされていませんでした。
少し探してみたのですが、末尾改行をclang-formatで設定する方法が見つかりませんでした。setting.jsonでは設定できるみたいです。
clang-formatでの書き方をご存知の方は教えてください🙇‍♂️

2024-06-03 11:08 UTC, YKhm20020 commented
> 確認なんだけど、マージする時には[ticket-KLI-29](https://github.com/KatLab-MiyazakiUniv/etrobocon2024/tree/ticket-KLI-29)での変更分は入れないってことだよね？

すみません、こちらの返信忘れていました🙇
本来はコンフィグファイルだけ分けてプッシュすべきなのですが、今回は二村君のファイルがないと動作確認ができないので入れています。
ここからコンフィグファイル以外を削って改めてプッシュしても大丈夫ですが、特に問題なければKLI-29の変更分をここでまとめてマージでいいと思います🙆‍♀

2024-06-03 13:32 UTC, KakinokiKanta commented
> > 確認なんだけど、マージする時には[ticket-KLI-29](https://github.com/KatLab-MiyazakiUniv/etrobocon2024/tree/ticket-KLI-29)での変更分は入れないってことだよね？
> 
> すみません、こちらの返信忘れていました🙇 本来はコンフィグファイルだけ分けてプッシュすべきなのですが、今回は二村君のファイルがないと動作確認ができないので入れています。 ここからコンフィグファイル以外を削って改めてプッシュしても大丈夫ですが、特に問題なければKLI-29の変更分をここでまとめてマージでいいと思います🙆‍♀

その場合は、[ticket-KLI-29](https://github.com/KatLab-MiyazakiUniv/etrobocon2024/tree/ticket-KLI-29)のレビューはこっちでやった方が良い？

2024-06-03 13:34 UTC, molpui0726 commented
> > > 確認なんだけど、マージする時には[ticket-KLI-29](https://github.com/KatLab-MiyazakiUniv/etrobocon2024/tree/ticket-KLI-29)での変更分は入れないってことだよね？
> > 
> > 
> > すみません、こちらの返信忘れていました🙇 本来はコンフィグファイルだけ分けてプッシュすべきなのですが、今回は二村君のファイルがないと動作確認ができないので入れています。 ここからコンフィグファイル以外を削って改めてプッシュしても大丈夫ですが、特に問題なければKLI-29の変更分をここでまとめてマージでいいと思います🙆‍♀
> 
> その場合は、[ticket-KLI-29](https://github.com/KatLab-MiyazakiUniv/etrobocon2024/tree/ticket-KLI-29)のレビューはこっちでやった方が良い？

こちらにお願いいたします！
二村君とは個別に連絡を取りつつ対応したいと思います🙇

2024-06-03 13:45 UTC, KakinokiKanta commented on module/EtRobocon2024.cpp
> +// }
俺もファイル末尾の改行に関しては、設定方法わからんかった...
このままで良いかも？とはなってる。明日の昼とかまでに誰もやり方を挙げなければ、このままで良いかも

2024-06-03 13:45 UTC, KakinokiKanta commented
> > > > 確認なんだけど、マージする時には[ticket-KLI-29](https://github.com/KatLab-MiyazakiUniv/etrobocon2024/tree/ticket-KLI-29)での変更分は入れないってことだよね？
> > > 
> > > 
> > > すみません、こちらの返信忘れていました🙇 本来はコンフィグファイルだけ分けてプッシュすべきなのですが、今回は二村君のファイルがないと動作確認ができないので入れています。 ここからコンフィグファイル以外を削って改めてプッシュしても大丈夫ですが、特に問題なければKLI-29の変更分をここでまとめてマージでいいと思います🙆‍♀
> > 
> > 
> > その場合は、[ticket-KLI-29](https://github.com/KatLab-MiyazakiUniv/etrobocon2024/tree/ticket-KLI-29)のレビューはこっちでやった方が良い？
> 
> こちらにお願いいたします！ 二村君とは個別に連絡を取りつつ対応したいと思います🙇

了解！

2024-06-03 17:09 UTC, bizyutyu approved these changes
タスク範囲に関しては、大丈夫だと思います。LGTM。![LGTM](https://image.lgtmoon.dev/208158)

2024-06-03 18:58 UTC, KakinokiKanta requested changes
コメントの書き方統一した方が良いかとも思ったんだけど、変更箇所多いし、どっちでも良いや。
このままで行きますって判断したら、コメントでリアクションくれれば、Resolveします

2024-06-03 18:58 UTC, KakinokiKanta commented on module/API/Measurer.h
> +   * 明るさを取得
```suggestion
   * @brief 明るさを取得
```
こんな書き方にしてほしい
[参考記事](https://qiita.com/inabe49/items/23e615649e8539d857a8)

2024-06-03 18:58 UTC, KakinokiKanta commented on module/API/Measurer.h
> +   * 右モータ角位置取得
```suggestion
   * @brief 右モータ角位置取得
```

2024-06-03 18:58 UTC, KakinokiKanta commented on module/API/Measurer.h
> +   * 左モータ角位置取得
```suggestion
   * @brief 左モータ角位置取得
```
ここも

2024-06-03 18:58 UTC, KakinokiKanta commented on module/API/Measurer.h
> +   * RGB値を取得
```suggestion
   * @brief RGB値を取得
```

2024-06-03 18:58 UTC, KakinokiKanta commented on module/API/Measurer.h
> +   * アームモータ角位置取得
```suggestion
   * @brief アームモータ角位置取得
```

2024-06-03 18:58 UTC, KakinokiKanta commented on module/API/Measurer.h
> +   * 正面から見て左ボタンの押下状態を取得
```suggestion
   * @brief 正面から見て左ボタンの押下状態を取得
```

2024-06-03 18:58 UTC, KakinokiKanta commented on module/API/Measurer.h
> +   * 正面から見て右ボタンの押下状態を取得
```suggestion
   * @brief 正面から見て右ボタンの押下状態を取得
```

2024-06-03 18:58 UTC, KakinokiKanta commented on module/API/Measurer.h
> +   * 中央ボタンの押下状態を取得
```suggestion
   * @brief 中央ボタンの押下状態を取得
```

2024-06-03 18:58 UTC, KakinokiKanta commented on module/API/Measurer.h
> +   * 超音波センサからの距離を取得
```suggestion
   * @brief 超音波センサからの距離を取得
```

2024-06-03 18:58 UTC, KakinokiKanta commented on module/API/Measurer.h
> +   * SPIKEの電圧を取得
```suggestion
   * @brief SPIKEの電圧を取得
```

2024-06-03 18:58 UTC, KakinokiKanta commented on test/dummy/ev3api_button.cpp
> +  //   }
```suggestion
```
確認に使ったやつ？残してる理由ないなら消した方が良いんじゃない？

2024-06-03 22:46 UTC, KeiyaNimura commented on module/API/Measurer.h
> +   * 明るさを取得
レビューありがとうございます。記事を参考にコメントの書き方を変更します。

2024-06-03 22:52 UTC, keiya121 commented on test/dummy/ev3api_button.cpp
> +  //   }
確認に使ったものです。消し忘れていました。
今後気を付けます！

2024-06-04 10:50 UTC, KakinokiKanta approved these changes
![LGTM](https://image.lgtmoon.dev/249761)

2024-06-04 11:12 UTC, merged